### ISSUE TITLE
[Go] home instead of back

### ISSUE THREAD

**Issue by ignacioch** [labooltd/GameAndroid#10]
Home functionality indeed.

**Comment by panagiotissp** [comment]
Case 1: If first time in a game in go page, i.e. first round of first team, before showing the question page. Clicking the home button in this case should just return to main menu page, without saving anything (save what anyway?!). Right?

Case 2: Otherwise, i.e. it will be a go page shown **after** a score page had been shown 1-3 screens before, where the game had been saved. So, in this case clicking the home button should just retunr to main menu page, without saving anything since it was already saved some screens ago. Right?

Case 1 && Case 2 => This button just returns to Main menu activity, and there is no save action.

Can the above claim be confirmed?

**Comment by ignacioch** [comment]
Case 1 :

Yes it should go to the main menu page. Nothing to be saved at all.

Case 2 :

When you click home you go to the main page anytime. But when you reload that game, you should open the go page of that team that was playing when home was clicked.

e.g. round 4, team A has played, team B is playing. I press home ==> go to main page. if I choose to resume, team B should play, on round 4, open Go page, with a new question. So, you save when a team has completed its turn essentially. 

Case 1 && Case 2 - I am not sure what you mean. You should always stick to what is on case 2 ( covers also case 1)

- you only save when the score screen is shown.
- any home takes you to main menu
- team that is playing does not save anything ( we haven't completed a round yet )

**Comment by panagiotissp** [comment]
This is a change to the functionality implemented. 
Always the last score page is opened when a saved game is resumed.

This should be changed and open the Go page always

**Comment by ignacioch** [comment]
Yes this is in order to match what we have on the final ios demo.

Sent from my phone, Sorry for typos.

On 21 Aug 2017, at 17:56, Panagiotis Spirou <notifications@github.com<mailto:notifications@github.com>> wrote:


This is a change to the functionality implemented.
Always the last score page is opened when a saved game is resumed.

This should be changed and open the Go page always

**Comment by panagiotissp** [comment]
So, for confirmation @ignacioch:
Up until now when a Previous game is resumed, the Score Page was opened.
Then in the Score Page it was decided if:
- game ended and a winner exists. In that case it loads Winner Page
- game ended and no winner exists. In that case it loads Sudden death Page
- game has not ended. In that case it loads Go Page (for next question to be played)

Now that we want the Go Page to be opened when a game is resumed, should the above be the handling again?
Concern is:
a game might be saved after last team of last round played. 
This means that when I click to 'resume' the game, it might e.g. take me immediately to the Winner Page (if a winner exists), so there is no 'resume' of the game actually.

Is this ok?

**Comment by ignacioch** [comment]
Miso gt mporei na yparxei ena confusion edw pera. den thymamai pws akrivws to exoume ylopoihsei sto android - alla nomizw ( epeidh etsi doulevei kai sto ios ) - oti :

- kanoume save to game status otan ftasoume sto score page - an dld to round teleiwsei, kai patithei next kai doume to score tote egine saved.

ara otan kanoume resume apo previous game, dn yparxei to prwto case pou les :

- an to game panw eixe teleiwsei, tote exei svhstei apo ta saved games.
- alliws tha einai se kapoio state - typou round 5, team B. ara anoigeis to go page me questions gia tn omada afth, se afto ton gyro.

- [ let me check gia to sudden death ti symvainei sto ios gt oi clients h dn to exoun testarei h einai happy me afto pou exoume - gia na eimaste consistent prepei na anoiksoume sto Go page, prin na paiksei h prwth omada to sudden death round ths. alla tha to tsekarw ti symvainei twra kai tha sou pw.

- genika nomizw to generic case einai to 3o panta - tha sou kanw confirm an to deftero einai separate case h oxi.



Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by panagiotissp** [comment]
The 1st case exists right now in Android:
- last team plays last question.
- Score page is loaded to show the new calculated score
- When user clicks 'next', the Winner Page is shown (if we have a winner), otherwise the Sudden Death Page

A video of the flow would help if this is possible

**Comment by ignacioch** [comment]
Nai afto einai swsto flow -

Your question was for the resume - after you show the score then game should be deleted ( and then yes you show the congratulations page). I mean after final score is shown - you cannot resume that game since there is nothing to resume. If the user hasn't seen the congrats page we don't care.

An to game dn einai finished tote nai an to kanei save kai gyrisei prepei na to synexisei apo to go page prin tn epomenh erwthsh ( opws lew sto last email)

Sent from my phone, Sorry for typos.

On 22 Aug 2017, at 13:22, Panagiotis Spirou <notifications@github.com<mailto:notifications@github.com>> wrote:


The 1st case exists right now in Android:

  *   last team plays last question.
  *   Score page is loaded to show the new calculated score
  *   When user clicks 'next', the Winner Page is shown (if we have a winner), otherwise the Sudden Death Page

A video of the flow would help if this is possible

**Comment by panagiotissp** [comment]
Ok then, this is not included currently. I will add the functionality to delete a saved game when a winner is found and the Winner page is to be loaded next.

I'm waiting for the clarification if the Sudden Death case is a separate one to handle, as you mentioned above.
 (since in the handling you mentioned, user may not even have seen that they are in 'sudden death' mode so it might be kind of weird to load a new Go page. This could occur, if user hits home button on the last score page of the game, exactly before the sudden death page is loaded)

**Comment by panagiotissp** [comment]
Ok thank you, I will change that also

**Comment by panagiotissp** [comment]
So, to sum up - only for my convenience to have it as to-do list:
- Make Sudden Death page to load in case of tie, after last question of the last team has just been played. (Currently, Score page is loaded first and on clicking next, the Score Page loads)
- Delete saved game if the game has ended, i.e. there is winner. (This in my implementation seems that should be done when the Score Page/Sudden Death Page loads. So: load the page, delete the saved game, on clicking 'next' button, the Winner page should open)
- Change functionality when a saved game loads, the Go page should open (and not the Score page of the last round played, which is the current implementation/initial specs, before the Go page was introduced)
