### ISSUE TITLE
[ Go ] font.

### ISSUE THREAD

**Issue by ignacioch** [labooltd/GameAndroid#102]
On the GO PAGE, the questions should be of bigger font size, they appear very small.

Please check from the excel, otherwise I cna send you what I used on IOS.

**Comment by panagiotissp** [comment]
@ignacioch  this question text  has exactly the same specs as question text on Question Page:
font size 15, font Roboto-condensed-bold

I do not remember that in the specs theere are 2 different cases written for question text on Go Page and on Question Page.

Should they be the same or not?
Please tell me what font size and which font you have put in order for me to put the same.

**Comment by ignacioch** [comment]
mikres othones : 16
medium : 19
big : 22 

kapws etsi to exw xwrisei sto iphone ( me ta antistoixa sizes of course ) - an thes na valeis ena mono tote vale to medium se ola.

**Comment by panagiotissp** [comment]
which is the number for xxxhdpi ? This is how we proceed this thing, and I will convert to correct dpi once provided.
