### ISSUE TITLE
[ Answers ] Spacing.

### ISSUE THREAD

**Issue by ignacioch** [labooltd/GameAndroid#104]
> Too much space under the final answer, especially on bigger screens.
> 
> For version 4.2.2 (Samsung galaxy 3 mini) we have the following  issue: Sometimes, we have to scroll down to see all answers, This happens ONLY when some answers take more than one line and there is a kotsana, so it is not very common. Ideally we would not have to scroll, but if there is no other way on small screens, then only the answers should scroll up and down, and not the question and clock.

**Comment by panagiotissp** [comment]
So I think it is better to copy that to issue #76 and handle them together. Current one seems to be a superset of #76 actually but the other is older.
So, I'm closing current ticket and copy @ignacioch comment above to that issue
