### ISSUE TITLE
FB text for sharing

### ISSUE THREAD

**Issue by ignacioch** [labooltd/GameAndroid#108]
I also think this is fixed - just on the apk they have. Check and close.

> When jokers are unlocked the share button at the end of a game should say: Partagez

**Comment by panagiotissp** [comment]
@ignacioch I want to clarify the 3 cases:
* When in NoJokersVersion (jokers locked from secret settings) this text should say "Partagez" and **without** the crown image.
* When in JokersVersion (jokers unlocked from secret settings) AND jokers not unlocked yet, this text should say "Partagez"and have the crown image too.
* When in JokersVersion (jokers unlocked from secret settings) AND jokers are unlocked, this text should say "Partagez"and **without** the crown image.

Do I understand correctly?

**Comment by panagiotissp** [comment]
If the above cases are correct, this issue is closed from commit 71a8527
