### ISSUE TITLE
[ Purchase ]

### ISSUE THREAD

**Issue by ignacioch** [labooltd/GameAndroid#109]
not sure what they mean or how they tested it in their demo but : 

 > When we close the app buying jokers simulation is reset. If these where purchased they should not be reset

probably will close after the new store implementation.

**Comment by panagiotissp** [comment]
@ignacioch this is normal, since implementation was to just test functionality.

Also, there is no point on having a separate issue "Purchase".. it goes under category of having Store implemented correctly. We have plenty of this kind of issues open, so I'm closing current one.
