### ISSUE TITLE
---phase2--- [Jokers Pages] Purchase locked jockers pop up.

### ISSUE THREAD

**Issue by panagiotissp** [labooltd/GameAndroid#11]
You had told me at some point that the popup may not be needed and, instead, just open the Store page.
So, is that the final answer?

**Comment by ignacioch** [comment]
No, use a popup ( default Android )

"Do you want to purchase Joker <name>" ? I can send you the names before final review.
When click yes, do the purchase. If cancel do nothing. 

App store you go just from the main screen.

**Comment by panagiotissp** [comment]
Is what you wrote above the final wanted deliverable for this issue?
Just a default popup window with 'yes' and 'cancel' and 'yes' button actually starting the purchase process of the locked product that was clicked?

**Comment by panagiotissp** [comment]
Also, is there any text and fonts provided for this? 
Otherwise, I will put a sample but in that case it needs to be remembered to be changed in the future..

**Comment by panagiotissp** [comment]
@ignacioch  I'm closing this. This is already handled elsewhere (in Store-related issues) and the current issue is pretty old and deprecated
