### ISSUE TITLE
 Screen that "vous n'avez ..." links to: Is that as initially requested?

### ISSUE THREAD

**Issue by panagiotissp** [labooltd/GameAndroid#13]
It is written in the last pdf that the customer shared with their last review, that it is to be confirmed what's going on with this "vous n'avez ..." text. A final answer is needed:
1) Does this text actually exists at all?
2) Is the corresponding page for the 'no-fb folks' still valid?

**Comment by ignacioch** [comment]
Phase 1 :
We will have no jokers. So screen looks like :
https://www.dropbox.com/s/5u8tpvmm3vuozvt/Photo%2014-07-2017%2C%2022%2056%2027.png?dl=0

and text is :
"Les jokers seront disponibles bientôt."

Once you click help - show custom Android alert that says : "Arrive bientôt"
All switches are unclickable for the time being and faded out.

Phase 2 :
- we will sort that out later.
