### ISSUE TITLE
---phase2--- [GameSettingsP2 Page] Help popup for locked jockers info.

### ISSUE THREAD

**Issue by panagiotissp** [labooltd/GameAndroid#14]
Please provide the corresponding texts and fonts.

**Comment by ignacioch** [comment]
That will be phase 2 - let's finish phase 1 first.

**Comment by panagiotissp** [comment]
I think we can close this issue and leave the corresp issue #11 open
(I do not see any point in having 2 issues for the locked jokers popup. If there is any objection, you may reopen the current issue of course)
