### ISSUE TITLE
[GameSettingsP2 Page] Help popup for foot mode info.

### ISSUE THREAD

**Issue by panagiotissp** [labooltd/GameAndroid#15]
Please provide corresponding texts and fonts.

**Comment by ignacioch** [comment]
Good catch I dont have it either. Font is : 

Roboto Condensed Bold
--

**Comment by ignacioch** [comment]
You can use in English - _Gives you access to 200+ football mode questions_

**Comment by panagiotissp** [comment]
![football_mode_specs](https://user-images.githubusercontent.com/14311142/31056530-cd09d04c-a6db-11e7-9e69-1ab3f95507d8.PNG)

Based on the screenshot from the specs that had been give, the help button should exist both in purchased(unlocked) and unpurchased(locked) version of football mode.
So, I'm implementing this.
