### ISSUE TITLE
[GENERAL] Fix english strings and french strings usage

### ISSUE THREAD

**Issue by panagiotissp** [labooltd/GameAndroid#17]

**Comment by ignacioch** [comment]
Do you need anything on that? Please find attached the latest file.

[App text final.xlsx (1).xlsx](https://github.com/labooltd/GameAndroid/files/1150375/App.text.final.xlsx.1.xlsx)

**Comment by panagiotissp** [comment]
For that, should I use localization (built-in in Android) and have both english strings and french strings, or customer wants only the french version anyway?

**Comment by panagiotissp** [comment]
@ignacioch  Another question, too (also please answer to the one above):
I was trying to close this issue by assigning the new texts contained in the new xlsx above.
- the above file does not contain the font sizes
- There are texts that have not been provided. 'Minimum 6 Categories', 'arrive bientot' (jokers disabled version popup), 'Mode Foot' text... 
- The file seems like a draft. It says '(Glamour) AKURO!' which is also in red. And there are other texts in red. What this means?

We have to clarify since this in general needs a lot manual work and inconsistencies between files means that I have to check all strings again manually

**Comment by panagiotissp** [comment]
@ignacioch I checked the xlsx file and compared to the older version and set the french strings for now.
Issues that I met:

**String no translation provided:**
- (Minimum 6 Categories)
- help popup jokers in no jokers version (now it is 'arrive a bientot' by ignatios)
- foot mode text + popup title + popup desc. Currently used:
'Mode Foot' and 'Gives you access to 200+ football mode questions'
- joker 'add 2 points to every answer'. Currently used:
'This joker adds 2 points to every answer\'s points'

**String with no english translation:**
- #60

**Don't know where the following strings are used:**
- string #79, 'Paquets de Jokers'
- string #80, 'Boutique' (in the explanation it says 'Different font then #4' which I do not understand)

**Different than original, not sure where to use:**
- Prices strings

I would be best for the customer to make a last review of the strings. (Or you could first review in case you already have some answers)

Waiting for your response on this one

**Comment by panagiotissp** [comment]
Also, there are strings with no english translation.
So, for the strings that in the 'english version' column do not have a value, I have no english text at all too.

Anyway, I did my job here, considering that the xlsx file is the latest version.

@ignacioch  I would suggest not to ask customer anything. 
(ignore my comments above, too)

They will review the app, not only once until the final review.
If the final review passes too, then this is supposed to be what customer wants anyway.

**Comment by ignacioch** [comment]
Re-opening that and assigning to me. I have some new strings.

**Comment by ignacioch** [comment]
I will update the issue after i see app on a device.

**Comment by ignacioch** [comment]
As said, remove English file. Only French.

**Comment by panagiotissp** [comment]
Ok @ignacioch  I'm closing this since its purpose of 'removing English strings' is actually duplicated by the issue #63 which I closed too.
