### ISSUE TITLE
[Score Page] Provide Animation info

### ISSUE THREAD

**Issue by panagiotissp** [labooltd/GameAndroid#19]

**Comment by ignacioch** [comment]
Again, mode info on Saturday.

**Comment by ignacioch** [comment]
https://www.dropbox.com/s/x1tosa1k91nzdqs/Video%2015-07-2017%2C%2015%2011%2016.mp4?dl=0

**Comment by ignacioch** [comment]
So bar of the team progresses. Total score is updated after the bar finishes its animation.

**Comment by panagiotissp** [comment]
(closed by mistake)

**Comment by panagiotissp** [comment]
One extra question here @ignacioch:
Should the bar animate when team got 0 extra points and have the same score as in the previous round?

**Comment by ignacioch** [comment]
No animation in this case.
