### ISSUE TITLE
[Winner Page] Provide Animation info

### ISSUE THREAD

**Issue by panagiotissp** [labooltd/GameAndroid#21]

**Comment by ignacioch** [comment]
Can you access that : https://www.dropbox.com/sh/x32lbqermt0jt1n/AAAuVbnQH4hXXjRdGIB2QpSna?dl=0

**Comment by panagiotissp** [comment]
yes, it opens without problems.

________________________________

**Comment by ignacioch** [comment]
Ok I will record it as well. This one is easier - we have a static image on the background and another one on top ( the one with the comfetis is a single image ) and the second one appears/disappears quickly.  Will record it with the other as well.

**Comment by ignacioch** [comment]
https://www.dropbox.com/s/t4hwe4kzbi65yd4/Video%2015-07-2017%2C%2015%2005%2017.mp4?dl=0

**Comment by ignacioch** [comment]
As I said above, background is always there, confetis is an image that blinks. Pick a frequency that makes it look like animation.

**Comment by panagiotissp** [comment]
(closed by mistake)
