### ISSUE TITLE
[GENERAL] Facebook share functionality.

### ISSUE THREAD

**Issue by panagiotissp** [labooltd/GameAndroid#22]
How it this implemented? Do we have the credentials needed?
Not sure, but I had a very quick look on that and took the following error:
![screenshot_2017-03-12-19-14-54](https://cloud.githubusercontent.com/assets/14311142/23836647/31552562-0784-11e7-8fd3-f80a0707feef.png)

**Comment by ignacioch** [comment]
I found the original email with what needs to be done. I will contact the client.

**Comment by ignacioch** [comment]
They send me this :

https://www.dropbox.com/s/jnqdqrmu2iae9fe/testers2.jpg?dl=0
https://www.dropbox.com/s/y2lpl1t8nlqrxyc/testusers.jpg?dl=0

**Comment by ignacioch** [comment]
do the above work?

**Comment by panagiotissp** [comment]
![fb-share-1](https://user-images.githubusercontent.com/14311142/31743183-dcd0a9a8-b462-11e7-8f2e-819f5dec5bfb.PNG)

![fb-share-2](https://user-images.githubusercontent.com/14311142/31743186-df5b7f9a-b462-11e7-918a-c20608dd3521.PNG)

@ignacioch  
What is the password for the user? I tested the user id even though I did not believe this is it

Have you tried it yourself?
Have the customer tried the share action and it worked? If not, I could put the jokers version on, which includes the share functionality in the Game Settings page 2, for the customer to test it too

**Comment by ignacioch** [comment]
Will try it on the device i got. I will request the password as well.

**Comment by ignacioch** [comment]
coming from clients : 


Chris singleton password: devineuf1
Nick Calathes password: devineuf2
James Feldeine password: devineuf3
Opten Graph password: devineuf4

**Comment by panagiotissp** [comment]
@ignacioch  yes this finally works!

the last question for this seems to be how to store the result of sharing on fb, so that when app opens again, the jokers will be unlocked.
A thought would be for an extra field to exist in the secret settings for that (since we have persistency there let's no create another file..).
The other option is to have it in another xml file.
The last is to have it in the shared preferences (although there less sensitive data are supposed to be stored, e.g. in our case previous games are stored that way)

Is there a suggestion/sth already implemented as logic in ios?

**Comment by panagiotissp** [comment]
no, sorry.
From what I remember jokers are locked-unlocked.
They can be unlocked in order to be used only through sharing on fb.

After that, joker functionality takes place if user enables it.
Then there are some jokers that can be directly used and some that need to be purchased (from Store)

So there is no flag for "jokers bought" (The ones from the store will be tried to be retrieved in app init as ww have said.)

**Comment by panagiotissp** [comment]
Anyway, @ignacioch  I implemented that.
If something is not aligned it will be found in the review process.

**Comment by panagiotissp** [comment]
Actually I'm reopening this since I do not have the text/link wanted to be included in the share action (probably lost somewhere in the emails).

@ignacioch could you please share what customer wants? 
From Fb guide https://developers.facebook.com/docs/sharing/android
there are some updates (e.g. "As of April 18, 2017, the following parameters are no longer supported by Graph API versions 2.9 and higher. For versions 2.8 and lower, the parameters will continue working until July 17, 2017.") 
so it is a good opportunity to clarify this.

**Comment by ignacioch** [comment]
Ack,will ask.

Sent from my phone, Sorry for typos.

On 29 Oct 2017, at 19:15, Panagiotis Spirou <notifications@github.com<mailto:notifications@github.com>> wrote:


Reopened #22<https://github.com/labooltd/GameAndroid/issues/22>.

**Comment by ignacioch** [comment]
Still waiting on this one, I have reminded them.

**Comment by ignacioch** [comment]
> 1. Unlock jokers: _USERΝΑΜΕ_vient d’activer les jokers pour rendre Devineuf encore plus intéressant! C'est le Quiz game convivial le plus fun pour s’amuser entre amis! www.devineuf.fr
>  
> 2. Share game: _USERΝΑΜΕ_vient de finir une partie Devineuf, le Quiz game de groupe le plus amusant! A ton tour de tester tes connaissances avec tes amis et de partager un moment convivial avec eux! www.devineuf.fr
> 
> Note: We would like the word Devineuf in both text be a link to the facebook page if possible.

**Comment by ignacioch** [comment]
Text came back from clients - check comment above.

**Comment by panagiotissp** [comment]
@ignacioch  have you implemented that on iOS??

From what I see this is not possible: 
Here https://developers.facebook.com/docs/sharing/android
it says "When you implement sharing, your app should not pre-fill any content to be shared. This is inconsistent with Facebook Platform Policy, see Facebook Platform Policy, 2.3."

and here is the platform policy: https://developers.facebook.com/policy/#control
and even here in the corresp video here (link included in the policty link): https://developers.facebook.com/docs/apps/review/prefill
it says (last 10 seconds) that prefilled messages is policy violation

I suppose the case is exactly the same for iOS, and that should be independent of platforms...

Also, the parameters that some time in the past handled this content, description, title etc, are now not supported, as I had said above. So, there are actually no fields to include your custom message (even though it will be a violation). 
E.g. I put in the code the following test:
![code-fb-share](https://user-images.githubusercontent.com/14311142/32703070-491b3a02-c7f9-11e7-8bcd-fe83e3e31389.PNG)

but nothing is shown in the app. Only the url is shown in the preview, which is actually the only supported field.

So, I don't understand what's going on here.
Supposedly, if my last comment above had been taken into account, these issues should have been found by the customer, or you - in case you have checked/implemented that.

So, what have you implemented? Am I missing sth obvious here?

**Comment by ignacioch** [comment]
not implemented yet on ios - text was received a couple of days ago. ok if that's not possible as it seems, then we dont support it. I will ask for clarifications.

**Comment by ignacioch** [comment]
in that case, text to be empty/no message - we just need the FB page app link? Or if not possible the website url.

Sent from my phone, Sorry for typos.

On 12 Nov 2017, at 20:39, Panagiotis Spirou <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #22<https://github.com/labooltd/GameAndroid/issues/22> to @ignacioch<https://github.com/ignacioch>.

**Comment by panagiotissp** [comment]
@ignacioch  I put exactly the same link as the one we have for the fb button on the Main Meu page, i.e. https://www.facebook.com/n/?devineuf

However, I have to mention that the moment I click the button to share , I see this:
![screenshot_20171118-144927](https://user-images.githubusercontent.com/14311142/32980653-35abdf70-cc73-11e7-9eb8-dab239400c9f.png)

which does not show the devineuf facebook page in the preview but the general facebook.com page.

I saw that the current fb link (https://www.facebook.com/n/?devineuf) actually redirects to https://www.facebook.com/devineuf
so I tried that instead.

However on that attempt what I got was even worse, and I got it **the moment** I clicked the button to share (I did not have any chance to create a 'post'):
![screenshot_20171118-145250](https://user-images.githubusercontent.com/14311142/32980647-ffee4bd4-cc72-11e7-9ff8-0b8b10a58461.png)


So, I'm not sure how to proceed with that since I do not know if this is sth as a setting or facebook forbids that or... 
I searched a lot online but found nothing tangible.
I reached to links like even that: https://www.facebook.com/menutab/posts/1274741965948898 (that's why I'm wondering if it is a setting on fb page)
and maybe the most useful link I found is this: https://stackoverflow.com/questions/42979010/web-sharing-not-working-could-not-share-post
but again does not help (it says they opened a bug ticket..)

I even thought of the this test user I loggedin with, Opten Graph, was deleted.
I tried with Chris user tough and got the same error message... but in French

What do you advise?

**Comment by ignacioch** [comment]
hmm lets try 2 things.

1) try to share a different url - one that is works as a url - e.g. www.sport24.gr or www.in.gr . if this works then it's a page issue - i will ask for a proper website.
2) if still the user is the issue - then maybe i need to tell them to create new users - which i would rather avoid.

3) worst case scenario because it needs work - we put the url to share in the secret settings and we build it generic. then it's their issue to fix. coding wise its done

**Comment by panagiotissp** [comment]
@ignacioch yes a generic link works as normal:
![fb-no-issue](https://user-images.githubusercontent.com/14311142/32985317-ce5282a4-ccc0-11e7-9b37-4b0840adde02.PNG)

So I suppose you will ask for normal website and I'm waiting for the new link to put on the share action?
Sending this issue back to you

**Comment by ignacioch** [comment]
as we said, tell me the file name and the variable name.

**Comment by panagiotissp** [comment]
@ignacioch the facebook url can be changed here:
app/src/main/java/fr/devineuf/LBGameData.java, current line 276
global variable APP_FACEBOOK_URL

I'm closing current ticket

**Comment by ignacioch** [comment]
can you change that so it uses a different variable?
https://github.com/labooltd/GameAndroid/blob/master/app/src/main/java/fr/devineuf/LBGameData.java#L278

the same global variable I think is being used for clicking on the fb item here : https://github.com/labooltd/GameAndroid/blob/5874d4190e97df9abf533d158b78a8236197a32c/app/src/main/java/fr/devineuf/MainMenuActivity.java#L418

so if they change that link to sport24.gr for example then the main page jump will also change. Please change to a different name - and the share one to use this name.

**Comment by panagiotissp** [comment]
APP_MAIN_PAGE_FB_URL is the new variable that is called on main page, so the APP_FACEBOOK_URL is now called only in the share actions

**Comment by ignacioch** [comment]
ok since they send me this - 

> Our landing page url is www.devineuf.fr

Please use that for APP_FACEBOOK_URL ( the one to share )
