### ISSUE TITLE
[Intro] Do we have animation?

### ISSUE THREAD

**Issue by ignacioch** [labooltd/GameAndroid#23]
Do we have an animation at the moment when app launches? If yes, close the issue.

If not here are the images - I will record my phone and set you how it should look like.

https://www.dropbox.com/sh/x32lbqermt0jt1n/AAAuVbnQH4hXXjRdGIB2QpSna?dl=0

**Comment by panagiotissp** [comment]
No, there is no animation in the app.
Ok, so the animation will be a number of images showing one after the other.
Please send the record you mentioned, or basically you may say the frequency that the images are shown one after the other, if there is a parameter like that used.

**Comment by ignacioch** [comment]
Ok, will send that in the evening today! Yes, just a number of images that are shown concecutively. Will paste the relevant information from iOS.

**Comment by ignacioch** [comment]
every 0.1s we change the image. I still owe the video but IOS does not have recording (!!) so I need to find to a second phone to record it - will do it in the weekend.

**Comment by panagiotissp** [comment]
I had many out of memory and latency problems due to the huge number of images having to be loaded in memory (about 100 images in total) in such a short time.
I have finally provided a solution to that, so I'm closing this issue.
