### ISSUE TITLE
Secret settings functionality

### ISSUE THREAD

**Issue by panagiotissp** [labooltd/GameAndroid#26]

**Comment by ignacioch** [comment]
will update the description until Saturday.

**Comment by panagiotissp** [comment]
Any update on this?

**Comment by ignacioch** [comment]
So, the idea is that we have an xml file where we read some configurations and these values are used in the app.

Example of the file is here : 

https://github.com/labooltd/GameOd/blob/master/GameOd/Resources/secret_settings.xml

Most of the names should be self explanatory but putting description here as well: 

- jokers : 1 means that jokers mode on, 0 means that the switch is off and cannot be toggled and we can't play with jokers. if you want to separate your releases and check both secret settings, set it to 0 and then the whole jokers things should be not "touchable".
- dump_answer_score : how much points the negative answer is.

The algorithm selection and the data collection path, I need to confirm if they are still in use. implement the above 2, for phase 1 delivery. Read the file on your launch, store them persistently and use these values accross all files.

**Comment by panagiotissp** [comment]
@ignacioch  I will close this ticket since I implemented the functionality for the 2 fields you mentioned above.

Please reopen if there is an update and sth needs to be changed.
