### ISSUE TITLE
[Questions Page] Use Clock image provided in the 'graphics'-related issue

### ISSUE THREAD

**Issue by panagiotissp** [labooltd/GameAndroid#27]

**Comment by panagiotissp** [comment]
Clock image provided in the new graphics pack is wrong... It is 1000x1000 (and I suppose this is for xxxhdpi).
Not sure about the other graphics yet, since I created a separate issue for that clock image to handle it and checked only that.

I'm sure they do not intend to use a 1000x1000 image for the clock.

@ignacioch I'm afraid I have to request (again) new graphic for that but I suppose better to do all other stuff first and leave that image empty for now until review (also maybe more issues occur with images again), right?

**Comment by ignacioch** [comment]
ok need to check this graphic - yes work on other issues first. I will check what they gave us and let's speak again with what we need.


Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by panagiotissp** [comment]
I believe this issue can be closed since there is the more general issue #30 mentioning the missing graphic of clock image too.
(If I'm missing sth please reopen it)
