### ISSUE TITLE
Handle any logging warnings/errors before release (even though app works fine)

### ISSUE THREAD

**Issue by panagiotissp** [labooltd/GameAndroid#29]
App works fine, but there are some cases where I see e.g. an error in the logging output.
Not sure right now why, have to check that.

**Comment by ignacioch** [comment]
We can skip warnings - please check just the errors.

Sent from my phone, Sorry for typos.

On 26 Aug 2017, at 00:21, Panagiotis Spirou <notifications@github.com<mailto:notifications@github.com>> wrote:


App works fine, but there are some cases where I see e.g. an error in the logging output.
Not sure right now why, have to check that.

**Comment by panagiotissp** [comment]
Cases found and are to be handled:

- E/ART: Failed sending reply to debugger: Broken pipe.
Cleared when clean/rebuild the app (https://stackoverflow.com/questions/31436157/e-art-failed-sending-reply-to-debugger-broken-pipe-but-application-still-runs)


- E/WVMExtractor: Failed to open libwvm.so: dlopen failed: library "libwvm.so" not found
This is a difficult one, cannot find though what is affected/what is the ""fix"" until now.

- AudioTrack: did not receive expected priority boost on time
This seems to be innocuous:
https://stackoverflow.com/questions/43255127/error-audio-priority-boost


- WindowManager: android.view.WindowLeaked: Activity com.spiroupanagiotis.gameod.MainMenuActivity has leaked window android.widget.PopupWindow$PopupDecorView{689b52b V.E...... .......D 0,0-1080,739} that was originally added here

This seems the important one to fix. It seems to be because I open the new Activity and not dismiss the popup Window of Main Menu page.
