### ISSUE TITLE
[Info] changes in info screen

### ISSUE THREAD

**Issue by ignacioch** [labooltd/GameAndroid#3]
- better distances
- mail to be clickable
- url to be clickable

**Comment by panagiotissp** [comment]
- Mail is clickable
- Url is clickable.

For 'better distances', from what I saw in the ios screenshot the customer had shared, it would probably be enough to put the mail block and the url block at the bottom of the screen (above the bottom menu).
If there is no objection, I'll do that.

**Comment by ignacioch** [comment]
Yes go on with that.
