### ISSUE TITLE
apk requested

### ISSUE THREAD

**Issue by panagiotissp** [labooltd/GameAndroid#31]

**Comment by panagiotissp** [comment]
[app-debug.zip](https://github.com/labooltd/GameAndroid/files/1326474/app-debug.zip)

**Comment by panagiotissp** [comment]
@ignacioch  you can find the requested apk in the comment above.

**Comment by ignacioch** [comment]
Great! Thanks Panagioti!

Sent from my phone, Sorry for typos.

On 23 Sep 2017, at 11:45, Panagiotis Spirou <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #31<https://github.com/labooltd/GameAndroid/issues/31>.

**Comment by ignacioch** [comment]
New apk this weekend?

**Comment by panagiotissp** [comment]
@ignacioch  I will be off this weekend, I would say that I have no new apk, but since I saw that:

[app-debug.zip](https://github.com/labooltd/GameAndroid/files/1363566/app-debug.zip)

Issue [GameSettingsP2 Page] Help popup functionality for foot mode info.
Issue [Options] resturer achats - I just closed that since the implementation is to check for internet connection only (handled in main menu page and under the issue to have full store functionality). No restore button in the options page

**Comment by ignacioch** [comment]
We definitely need a new apk this weekend.

**Comment by panagiotissp** [comment]
Here it is
[app-debug.zip](https://github.com/labooltd/GameAndroid/files/1380745/app-debug.zip)

**Comment by panagiotissp** [comment]
@ignacioch  updated apk with the latest commit:

[app-debug.zip](https://github.com/labooltd/GameAndroid/files/1383472/app-debug.zip)

It includes:
- Show all teams in Sudden death popup Mode
- Show continuous counting of Rounds in Sudden death Mode. **(this should be update to previous apk)**
- Reset Sudden death page UI to match Scores page UI. 
- Use smart banner instead of fixed banner in Main menu page banner since this probably will fit better to different screens  **(this should be update to previous apk)**

**Comment by panagiotissp** [comment]
@ignacioch 

new apk, includes:
- Sudden death popup implementation
- Usage of new db
- Fix inconcistency of category ids originating from db (this was what made it necessary to unselect 2 categories - otherwise app crashed)
- Remove glamour pack/category (issue #38 in case you missed it)


[app-debug.zip](https://github.com/labooltd/GameAndroid/files/1405389/app-debug.zip)

**Comment by panagiotissp** [comment]
Apk 1 November : 
[app-debug.zip](https://github.com/labooltd/GameAndroid/files/1435428/app-debug.zip)

@ignacioch  please use this newest apk for the pending for approval/double check issues.

**Comment by panagiotissp** [comment]
Latest Apk with setup of Rate me functionality:
 
[app-debug.zip](https://github.com/labooltd/GameAndroid/files/1435926/app-debug.zip)

**Comment by panagiotissp** [comment]
The following has jokers enabled (from secret settings):
[app-debug-jokers-enabled.zip](https://github.com/labooltd/GameAndroid/files/1447989/app-debug-jokers-enabled.zip)

The following has the jokers disabled (from secret settings):
[app-debug-jokers-disabled.zip](https://github.com/labooltd/GameAndroid/files/1448017/app-debug-jokers-disabled.zip)

**Comment by panagiotissp** [comment]
last apk with jokers enabled:
[app-debug-jokers-enabled.zip](https://github.com/labooltd/GameAndroid/files/1459121/app-debug-jokers-enabled.zip)

last apk with jokers disabled:
[app-debug-jokers-disabled.zip](https://github.com/labooltd/GameAndroid/files/1459128/app-debug-jokers-disabled.zip)

**Comment by ignacioch** [comment]
Please a new apk today with debug mode off to be able to create the store setup for Android.

you can send me the non-jokers version ( or both ).

**Comment by ignacioch** [comment]
https://stackoverflow.com/questions/32263949/you-uploaded-a-debuggable-apk-for-security-reasons-you-need-to-disable-debuggin

or

https://stackoverflow.com/questions/19994874/unable-to-upload-new-apk-file-to-android-play-store

**Comment by panagiotissp** [comment]
@ignacioch  that should be it, I have attached it at the end of this comment.
However, it needs to be checked in the Store where the previous apk failed. 
Fyi, for my future reference mainly, I created this apk by setting the 'build variant' to  'release':
![build-variants](https://user-images.githubusercontent.com/14311142/32803049-eebfe45c-c98a-11e7-9401-30ce17cccd4b.PNG)

Waiting for your feedback. 

[app-release-unsigned.zip](https://github.com/labooltd/GameAndroid/files/1472424/app-release-unsigned.zip)

**Comment by ignacioch** [comment]
@@ still not working.

issue is : 
You uploaded an APK with an invalid signature (learn more about signing). Error from apksigner: ERROR: JAR_SIG_NO_SIGNATURES: No JAR signatures

--> https://stackoverflow.com/questions/44816305/upload-new-apk-to-alpha-failed

FYI, I created/purchased a new developer account so I can build/setup the store on my own before the clients do, so please check how to fix the above issue and I will try if first on my side.

In the error there is also this link : 
https://developer.android.com/studio/publish/app-signing.html

**Comment by ignacioch** [comment]
FYI you can try on my account to see if the apk is suitable : 

ignatiosch@gmail.com
P2nas0qe!!

and i have 2-factor enabled so send me a message before so that I send you the password from the message.

Log in : https://play.google.com/apps/publish/?account=7508807372917225808#AppListPlace

Select DevineUf_t
--> In App products
--> Upload apk.

if it succeeds, then this is the apk we need to send to the clients to create their own.

**Comment by panagiotissp** [comment]
yes this is what I was afraid of.. sigint the apk.
It needs keystores/certificates.. things like that (that I do not remember anymore, I will read the docs again).
My concern is if this actually binds the domain and app names (the 'panagiotisspirou' part and the 'GameOd') and if that is so, then these should first be handled...

This issue (store setup and testing) should be our priority.
I will investigate when I have the time

**Comment by ignacioch** [comment]
Yes that's why I created he other issue.

Check my developer account that I created - and let's try to create the store there ( upload apk and sign and everything) - it's the same we did in iOS ( use our account since clients don't give their password).



Sent from my phone, Sorry for typos.

On 15 Nov 2017, at 08:59, Panagiotis Spirou <notifications@github.com<mailto:notifications@github.com>> wrote:


yes this is what I was afraid of.. sigint the apk.
It needs keystores/certificates.. things like that (that I do not remember anymore, I will read the docs again).
My concern is if this actually binds the domain and app names (the 'panagiotisspirou' part and the 'GameOd') and if that is so, then these should first be handled...

This issue (store setup and testing) should be our priority.
I will investigate when I have the time

**Comment by panagiotissp** [comment]
@ignacioch apk release version (I will share with you signed credentials for keystore and key):

[app-release.zip](https://github.com/labooltd/GameAndroid/files/1485792/app-release.zip)

**Comment by ignacioch** [comment]
for logging issues : 

jar_signature -> https://stackoverflow.com/questions/44816305/upload-new-apk-to-alpha-failed

**Comment by panagiotissp** [comment]
@ignacioch apk with jar signature included, which was the reason apk above failed:

[app-release.zip](https://github.com/labooltd/GameAndroid/files/1485814/app-release.zip)

**Comment by panagiotissp** [comment]
@ignacioch  latest apk, all fixes, with product ids (the ones setup in Store) included:


[app-release.zip](https://github.com/labooltd/GameAndroid/files/1493411/app-release.zip)

**Comment by ignacioch** [comment]
Jokers on or off in this one?

I need both.

Sent from my phone, Sorry for typos.

On 21 Nov 2017, at 23:50, Panagiotis Spirou <notifications@github.com<mailto:notifications@github.com>> wrote:


@ignacioch<https://github.com/ignacioch> latest apk, all fixes, with product ids (the ones setup in Store) included:

app-release.zip<https://github.com/labooltd/GameAndroid/files/1493411/app-release.zip>

**Comment by panagiotissp** [comment]
@ignacioch 
release apk with jokers on:
[app-release-jokers-on.zip](https://github.com/labooltd/GameAndroid/files/1497127/app-release-jokers-on.zip)

release apk with jokers off:
[app-release-jokers-off.zip](https://github.com/labooltd/GameAndroid/files/1497136/app-release-jokers-off.zip)

**Comment by panagiotissp** [comment]
@ignacioch here are the new apks with different version numbers and names.

jokers off:
[app-release-jokers-off.zip](https://github.com/labooltd/GameAndroid/files/1500030/app-release-jokers-off.zip)

jokers on:
[app-release-jokers-on.zip](https://github.com/labooltd/GameAndroid/files/1500033/app-release-jokers-on.zip)

**Comment by panagiotissp** [comment]
@ignacioch new release apks for the issue #76 that should now be ok
[app-release-jokers-off.zip](https://github.com/labooltd/GameAndroid/files/1503972/app-release-jokers-off.zip)
[app-release-jokers-on.zip](https://github.com/labooltd/GameAndroid/files/1503973/app-release-jokers-on.zip)

**Comment by ignacioch** [comment]
Please provide both with changed version codes as well.

**Comment by panagiotissp** [comment]
[app-release-final-jokers-on.zip](https://github.com/labooltd/GameAndroid/files/1519327/app-release-final-jokers-on.zip)
[app-release-final-jokers-off.zip](https://github.com/labooltd/GameAndroid/files/1519328/app-release-final-jokers-off.zip)

**Comment by panagiotissp** [comment]
@ignacioch as you correcly said, above apks have the same older versionCode since I completely forgot to change it.

Here is the version with jokers on and new versionCode (I'm uploading only one apk with jokers on, as we discussed on messenger):

[app-release-final-jokers-on.zip](https://github.com/labooltd/GameAndroid/files/1519523/app-release-final-jokers-on.zip)

**Comment by panagiotissp** [comment]
@ignacioch last release apks including the 2 extra fixes customer asked:

[app-release-jokers-off.zip](https://github.com/labooltd/GameAndroid/files/1522744/app-release-jokers-off.zip)
[app-release-jokers-on.zip](https://github.com/labooltd/GameAndroid/files/1522745/app-release-jokers-on.zip)
