### ISSUE TITLE
Implement Store full functionality

### ISSUE THREAD

**Issue by panagiotissp** [labooltd/GameAndroid#32]
- Make it possible to purchase items and unlock the corresponding functionalities.
- Setup logic to load any purchased items on app init. (on failure just show an error message and use no purchased items for the gameplay - see discussion on issue #7 )

**Comment by panagiotissp** [comment]
Is there a Store setup already @ignacioch  with items etc?

**Comment by ignacioch** [comment]
Need to check that - I dont think there is ( we dont have for ios as well ).

**Comment by ignacioch** [comment]
Assigned to me until I have the answer. 

Basically what we need again is : 
- sending clients an email saying what they have to do. e.g. you need to create this, and then follow this tutorial to create these items, and then we need back these ids etc.

**Comment by ignacioch** [comment]
Send email to clients.

**Comment by ignacioch** [comment]
Update from the email : they have a dev account so they want to tell them what to setup and how. any tutorials around that they can follow? I will search as well / asking just in case you have seen any already.

**Comment by panagiotissp** [comment]
@ignacioch  I'm trying to setup a store functionality using your account, but I cannot login (you had shared the credentials 2 years ago)
Could you help with that?

No, I do not know what they should do, I do not know the UI so I have to check it first

**Comment by ignacioch** [comment]
Probably mine is expired - leave this with me and go on with the rest issues. I will try to find out what is needed and tell clients to fix them ASAP.

Sent from my phone, Sorry for typos.

On 29 Oct 2017, at 19:53, Panagiotis Spirou <notifications@github.com<mailto:notifications@github.com>> wrote:


@ignacioch<https://github.com/ignacioch> I'm trying to setup a store functionality using your account, but I cannot login (you had shared the credentials 2 years ago)
Could you help with that?

No, I do not know what they should do, I do not know the UI so I have to check it first

**Comment by ignacioch** [comment]
We need a demo with debugging mode off. check screenshot on fb messenger.

**Comment by panagiotissp** [comment]
@ignacioch 
Store functionality implemented with test values for items.
Ready for review.
Because there is an issue with Store not making it able to have by default the purchased items get reset everytime, in order to be able to test the purchase again, I have explicitly written code that resets the Football Pack on the GameSettings Page 2.

This is only for testing purposes for now and should be removed when test is finished.
All other items right now should show an error message in the form of "item is not found", but the process always is triggered.

Restore purchases is also implemented but again, fetches nothing since I cannot mimic the inventory..

**Comment by panagiotissp** [comment]
Reopening since implementation needed to be able to purchase football pack from Categories Page too
