### ISSUE TITLE
[Sudden Death Page] Provide Animation info

### ISSUE THREAD

**Issue by panagiotissp** [labooltd/GameAndroid#33]
An extra question here is:
What is the animation shown the first time we show the Sudden death page? e.g.:
- last team, team 4, plays last round.
- they get 2 points on this last question, making their score equal to the maximum score which only team A had until that point.
- they click 'next' button on the Question page after having collected the 2 points
- Sudden death page should be shown, sudden death "modal" is shown, sudden death sound is played etc.
Should the score of this last team been animated as normal?

**Comment by ignacioch** [comment]
No animation happens at this point , just show the "modal" of sudden death.

In more details : 

Score animation is shown only on the score screen - in the case of sudden death we are skipping the normal screen and this is replaced with the "sudden death" case therefore no animation.

This is what happens on IOS right now and we didn't have any feedback to change it.

**Comment by panagiotissp** [comment]
Ok so **whenever** the sudden death page loads to show the points (either for first time that includes the modal, or not) there is no animation at all, just the new bars' length based on the new score. I will go that direction since customer agrees based on what you say.
Thank you
