### ISSUE TITLE
[Sudden Death Page] Determine team layouts allocation

### ISSUE THREAD

**Issue by panagiotissp** [labooltd/GameAndroid#35]
Should the layouts of the teams playing in Sudden death been "compressed" in the Score page?

E.g. if team 1 and team 4 (4 teams were playing) go to sudden death, should the score page have the team layouts allocated as initially (with all teams playing) or e.g. compressed to the top?

A screenshot of this example case in iOs would help to clarify it

**Comment by ignacioch** [comment]
Yes, in a game of 4 teams - if team 1 and 4 go to sudden death then, team 4 will be placed in the position of team 2 etc. Sending screenshots as well.

**Comment by ignacioch** [comment]
On final round : https://www.dropbox.com/s/ny1lflrkcbqyppk/Photo%2007-10-2017%2C%2014%2011%2030.png?dl=0

Team 1 and team 3 go to sudden death.

Then the new score screen becomes : 
https://www.dropbox.com/s/ek0yahx7nuymike/Photo%2007-10-2017%2C%2014%2011%2051.png?dl=0

so team 3 moved in team's 2 position.
