### ISSUE TITLE
Close current activity after loading the next one

### ISSUE THREAD

**Issue by panagiotissp** [labooltd/GameAndroid#41]
This should be done for all activities.
Only exception might be the Main menu page where there are 2 options:
- Leave it forever in stack, so when hitting back (or even 'Home') on an activity to show the MainMenu page
- Remove that too as normal, and just reopen it when needed ('Back' button is hit, or 'Home' is hit)

@ignacioch  what is your implementation?

**Comment by ignacioch** [comment]
IOS does not have the same concept - but it uses something similar to stack. So I Am fine with either way - just make sure that every time we hit back the previous screen loads correctly.

If this is happening I am.fine with any implementation.

Sent from my phone, Sorry for typos.

On 24 Oct 2017, at 01:39, Panagiotis Spirou <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #41<https://github.com/labooltd/GameAndroid/issues/41> to @ignacioch<https://github.com/ignacioch>.
