### ISSUE TITLE
[Initial Screen][Feedback Round 1] Fix links

### ISSUE THREAD

**Issue by ignacioch** [labooltd/GameAndroid#43]
Facebook: https://www.facebook.com/devineuf/ 

Twitter: https://twitter.com/k8appton 

If native app exists open it there. otherwise browser (if possible - in IOS this is trivial )

**Comment by panagiotissp** [comment]
It does not seem obvious unfortunately: https://stackoverflow.com/questions/34564211/open-facebook-page-in-facebook-app-if-installed-on-android


Still checking

**Comment by panagiotissp** [comment]
@ignacioch  there has been a related deploy for this case, as referenced in the commit above.

As I mentioned in another issue, I currently have problem with my device and I cannot test it.
If in the meantime you had the time to test it, it would help a lot (click links with app(s) installed, click links with app(s) not installed etc)

**Comment by panagiotissp** [comment]
Actually I tested that and it works, so I'm closing this.

Please, however, leave your comment here when you double check if everything is ok.
