### ISSUE TITLE
[Feedback Round 1] Rate me

### ISSUE THREAD

**Issue by ignacioch** [labooltd/GameAndroid#44]
App needs to have a rate me component. Dont build yourself - in IOS I used a library component. On Android I found this one - can you check whether it's easy to import.

https://github.com/hotchemi/Android-Rate

**Comment by ignacioch** [comment]
There is also this if you want custom implementation : https://stackoverflow.com/questions/14514579/how-to-implement-rate-it-feature-in-android-app

**Comment by panagiotissp** [comment]
@ignacioch I just put a commit related to this (using the library you sugggested) and the corresponding latest apk which includes this here:
on issue #31 

Please review. I have currently a problem with my android device, and I only test on Emulator. Unfrotunately this cannot be tested though.

If everything works ok for you, could you please send me the corresponding texts and configuration needed? 
It is what is mentioned in the Readme of that library plus the texts mentioned there too.
(If there is sth I should clarify please tell me)

Also, as an extra note, it seems that this rate me library needs google play services installed to work.
I have put a check in the code to handle this, but I do not know what to do in this case.. probably nothing? 
(not sure how to test that too.... )
Any suggestions/ideas are welcome.

Waiting for your reply

**Comment by ignacioch** [comment]
This is working ( I mean it takes you to store but cannot find anything - I assume when we have the url or something there it will work ) but : 

- [ ] every time I go back on MAIN screen I see it. Is there a setting to prevent that?
- [ ] If I click No,thanks / Remind me Later - they don't work, I keep still seeing the popup.

**Comment by ignacioch** [comment]
Sending you the IOS parameters : 

```
 //configure iRate
    [iRate sharedInstance].daysUntilPrompt = 7;
    [iRate sharedInstance].usesUntilPrompt = 10;
    
    [iRate sharedInstance].message = NSLocalizedString(@"990", nil);
    [iRate sharedInstance].rateButtonLabel = NSLocalizedString(@"991", nil);
    [iRate sharedInstance].cancelButtonLabel = NSLocalizedString(@"992", nil);
    [iRate sharedInstance].remindButtonLabel = NSLocalizedString(@"993", nil);
    [iRate sharedInstance].messageTitle = @"";
```

Where strings are : 

`"990" = "Vous prenez plaisir à jouer à Devineuf ? Si c'est le cas n'hésitez pas à noter l'application.";
"991" = "Noter l'application" ;
"992" = "Noter plus tard" ;
"993" = "Non merci" ;`

**Comment by ignacioch** [comment]
For the rest you can leave the default.

**Comment by ignacioch** [comment]
The showing always should be because of the : 

 .setDebug(true) // default false

so can we try that instead : make it false for now, and see if it appears or not -> click no thanks and check again.

I think it looks ok so we can be sure it works - it's a library component that is supposed to be working and we integrated that. I am having the same on IOS so probably best to remove the setDebug and then close the issue.

**Comment by panagiotissp** [comment]
@ignacioch I set the reminder interval ('remind me later') to be 2 days since you did not provide that value.
I removed the debug flag so it should now be working as normal. (i.e when the conditions are met).

I have also added handling so that:
If GooglePlayServices is no available, or Google Play Store has been uninstalled or Google Play Store has been disabled, the RateMe dialog is never shown at all (As I wrote above, these cases are unhandled inside the library, making the app crash).
I think this is ok since anyway users with disabled/uninstalled Google Play Store is an edge case.

Please confirm that this handling ok.

**Comment by panagiotissp** [comment]
I'm attaching a screenshot for the Rate me dialog too here below:
![rateme-french](https://user-images.githubusercontent.com/14311142/32416334-5feb59b4-c250-11e7-8fa5-e0c374b67629.png)

**Comment by ignacioch** [comment]
Seems good, issue is closed.

Sent from my phone, Sorry for typos.

On 5 Nov 2017, at 15:40, Panagiotis Spirou <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm attaching a screenshot for the Rate me dialog too here below:
[rateme-french]<https://user-images.githubusercontent.com/14311142/32416334-5feb59b4-c250-11e7-8fa5-e0c374b67629.png>
