### ISSUE TITLE
[Initial Screen][Feedback Round 1] Wrong images on popup.

### ISSUE THREAD

**Issue by ignacioch** [labooltd/GameAndroid#45]
On the popup - when a saved game already exists, both images are wrong. Not sure if you have the correct ones - if you dont have them, I will request again.

This is what it should look like 

https://www.dropbox.com/s/0h0vv5z5mm0cw3o/Photo%2029-10-2017%2C%2014%2002%2059.png?dl=0

**Comment by panagiotissp** [comment]
@ignacioch 
There is big issue with graphics. Yes I do not have these graphics.

I had mentioned it here too: https://github.com/labooltd/GameAndroid/issues/18
and even put a screenshot.

Also, there is the issue #30 that has some missing graphics.
What approach do you prefer? Separate issue for each graphic (as you did on current issue)? Or a single issue for all as #30 ?

**Comment by panagiotissp** [comment]
Closing this since all the rest of missing/problematic graphics will be handled under #67
