### ISSUE TITLE
[Round Selection Screen][Feedback Round 1] Change demo button from 5 to 10.

### ISSUE THREAD

**Issue by ignacioch** [labooltd/GameAndroid#47]
2nd button is set to 5 ( or 2 inherently I think for demo purposes ). Just putting as an issue so that we remember to change it back.

You can do that from now - 5 rounds for demo purposes is not so bad.

**Comment by ignacioch** [comment]
So that's missing as well. Requesting.

**Comment by panagiotissp** [comment]
Added back correct round button graphics to be displayed (according to the more generic #67 issue) and also the correp logic behind the buttons (correct number of round to be set).

This is closed by commit e8ee0b5b
