### ISSUE TITLE
[Round Selection Screen][Feedback Round 1] Jokers Popup when JokersMode is OFF.

### ISSUE THREAD

**Issue by ignacioch** [labooltd/GameAndroid#48]
So - I am not sure if the JokersMode is OFF from secret settings. If it is working as expected then send me an apk I can verify it and I will close the issue.

When jokers is OFF this is what should happen : 

- [x] Text should be : "Les jokers seront disponibles bientôt."
- [x] FB sharing should not be clickable / same with unlocking / buying
- [x] Use default toast as we said on previous issue. Text for this one  ""Les Jokers vous aident à remporter la partie: vous en disposez 6 et sont repartis en deux groupes. Le premier groupe vous permet de booster votre score pendant votre tour de jeu. Lorsque c'est au tour de l'adversaire de rèpondre à une question, le deuxième groupe de jokers vous permet de lui mettre les bâtons dans les roues. Chaque équipe peut utiliser un maximum de 3 jokers. Pour les parties à plus de 2 équipes, le deuxième groupe n'est pas disponible."

**Comment by panagiotissp** [comment]
[app-debug.zip](https://github.com/labooltd/GameAndroid/files/1432420/app-debug.zip)

@ignacioch  this should be the case.

I'm sending you an apk attached on this comment having disabled the jokers functionality in the secret settings.
So, everything should be as you described.

Please close current ticket if everything is ok after you double check.

**Comment by ignacioch** [comment]
Nice will check.

**Comment by ignacioch** [comment]
In the latest APK, jokers should be off as you said. If that's the case then the below do not work.

- [ ] FB share is clickable
- [ ] Text "Partagez" etc should be replaced with the text in 1st bullet --> ""Les jokers seront disponibles bientôt."

( unless the latest apk has then ON in secret settings )

**Comment by panagiotissp** [comment]
@ignacioch  that is correct, both are exactly as you mentioned: Fb/switch is **not** clickable and text  is the wanted one: "Les jokers seront disponibles bientôt."

Attaching a screenshot below:
![no-jokers](https://user-images.githubusercontent.com/14311142/32414396-29298ada-c22e-11e7-9a4a-7f4a2e8ce398.PNG)


And attaching another apk here below which has jokers disable in secret settings, for you to triple check.
[app-debug-no-jokers-version.zip](https://github.com/labooltd/GameAndroid/files/1443961/app-debug-no-jokers-version.zip)


I'm closing this ticket but please let's verify it when you have 2 minutes spare to be 1000% sure.
