### ISSUE TITLE
[Round Selection Screen][Feedback Round 1] Mode Foot Popup

### ISSUE THREAD

**Issue by ignacioch** [labooltd/GameAndroid#49]
- [x] change text to Foot Mode
- [x] make the popup a toast
- [x] change the text in the popup. New one should be ""Ce mode de jeu est indispensable pour les passionnés de football! 
Testez vos connaissances en jouant avec des questions uniquement sur le foot et remportez la coupe!"

**Comment by panagiotissp** [comment]
@ignacioch it already is a toast in the new apk (both help popups in this page should be)

I changed text from 'Mode Foot' to 'Foot Mode' (hope this is what you meant with the 1st bullet)

Also I put the text you provided above.
I have to say though that the english text from the "latest strings" excel file is
'Gives you access to 200+ football mode questions' which does not match the translation, but anyway...

I'm closing current ticket
