### ISSUE TITLE
[Options page] Implement help button

### ISSUE THREAD

**Issue by ignacioch** [labooltd/GameAndroid#5]
If you need text please let me know.

**Comment by panagiotissp** [comment]
I need text yes, I need this text and all help popups' text that exist in the app (a new issue is better to be opened I think though).

**Comment by ignacioch** [comment]
When clicking on stats you need a popup.

Here is the text

"Pour rendre le jeu plus intéressant et afin d'adapter la difficulté des questions, nous analysons votre parcours et nous créons des statistiques.  L'objectif est de rendre le jeu plus équilibré et surtout plus amusant pour tous."

This is how it should looks like :

https://www.dropbox.com/s/hnwaen8h2nu5mvd/Photo%2014-07-2017%2C%2022%2022%2043.png?dl=0

if you dont have the images tell me and I will find the Android ones.Let me know. In the meantime use the Android default alert box.
