### ISSUE TITLE
[Categories][Feedback Round 1] Categories screen UI.

### ISSUE THREAD

**Issue by ignacioch** [labooltd/GameAndroid#50]
A few changes on the UI.

- [x] Once I select <6 categories, tick button should be faded out- reduce alpha to 0.5 ( not disappear ). Color of minimum 6 text should become red.
- [x] The locked button on the football pack should be in the position of the normal logo. If bought then we should see the football one. If it's not bought we should only see the locked. I will also attach a screenshot on IOS.

**Comment by panagiotissp** [comment]
![locked-categ](https://user-images.githubusercontent.com/14311142/32252064-60526c88-be9c-11e7-8152-dd53609ba1d7.PNG)
![unlocked-categ](https://user-images.githubusercontent.com/14311142/32252066-61b50b3a-be9c-11e7-88cb-db25d143c72d.PNG)


@ignacioch  I believe this is what you meant.

Please confirm (and if not, reopen the issue with a screenshot clarification, as you wrote)

**Comment by ignacioch** [comment]
Yes that's what I meant for the locked icon. Thanks!

Sent from my phone, Sorry for typos.

On 31 Oct 2017, at 22:43, Panagiotis Spirou <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #50<https://github.com/labooltd/GameAndroid/issues/50> via d95ff34<https://github.com/labooltd/GameAndroid/commit/d95ff34b92a5e58940ffaffd9ebc29755c83d768>.
