### ISSUE TITLE
[Logic][Feedback Round 1] bug found in game logic.

### ISSUE THREAD

**Issue by ignacioch** [labooltd/GameAndroid#51]
Try to reproduce by doing : 

- Start  a game, go until a point and then exit. Supposedly this game should be saved now.
-  Go to initial screen, start a new game.

( maybe the below are not required but we can check )
- select categories, leave <6 checked.
- click back ( no save of categories )
- click next to start the game

**BUG** the team / round from the old game continue ( game on step 1 ) - even though we started a new gane.

**Comment by panagiotissp** [comment]
@ignacioch  The thing here is your 2nd bullet: How do you go to initial screen??
Functionality of "Home" did not work (properly) until the deploy that fixed issue #41 

Can you please clarify this?
Since it might have been fixed by that deploy

**Comment by ignacioch** [comment]
well ideally should be by home. In that example - I closed the app and re-opened, and it's like it continued from where I was. Anyway let me check with number #41 fixed and I will close it if it is not reproducable anymore.

**Comment by ignacioch** [comment]
works now, thanks!
