### ISSUE TITLE
[Crash][Feedback Round 1] Saved games 

### ISSUE THREAD

**Issue by ignacioch** [labooltd/GameAndroid#52]
When we have saved games, clicking on the popup which should open the 'saved games' screen makes it crash.

**Comment by panagiotissp** [comment]
@ignacioch I cannot reproduce.

![clicking saved games](https://user-images.githubusercontent.com/14311142/32243871-6a67d86a-be7f-11e7-9b89-16bada108fc1.PNG)
![open saved games](https://user-images.githubusercontent.com/14311142/32243882-6e3260c8-be7f-11e7-8242-f8d279df9d92.PNG)


You cannot open the page shown in 2nd screenshot when you click 'Previous game' from 1st screenshot?

**Comment by ignacioch** [comment]
Now i can - hmm weird, maybe it had to do with #51 and #41 - will check again

**Comment by ignacioch** [comment]
Another thing is ( like #63) why is text in English?

**Comment by panagiotissp** [comment]
French is the default language, but if locality matches English version, then it is "smart" enough to use the localized strings, i.e. English in this case.

**Comment by ignacioch** [comment]
Works now - closing.
