### ISSUE TITLE
[Question screen][Feedback Round 1] Home works as back.

### ISSUE THREAD

**Issue by ignacioch** [labooltd/GameAndroid#54]
Basically that's on other screens as well. Once game is started, home should exit ( we had discussed when a game is saved before - I can find the issue/email if needed ).

The UI is correct but functionality is wrong - in every screen that has the home , we should go back to home screen. Every screen that has the back - should take us back to previous screen.

**Comment by panagiotissp** [comment]
This is supposed to be resolved with the fix of issue #41
