### ISSUE TITLE
[Score Screen][Feedback Round 1]  animation issue - handle negative points

### ISSUE THREAD

**Issue by ignacioch** [labooltd/GameAndroid#56]
On negative points animation does not work. We need it to work - for example : 

- if I have 7 pts and I get -5 on the round, bar should go from 7 to 2.
- if I have 3 pts and I get -5, bar should go from 3 to 0 ( it can't go below 0 ).

**Comment by panagiotissp** [comment]
So @ignacioch  for the cases you mentioned, bar should animate from current value to new value?
Or from zero to new value?
E.g. from 7 to animate down to 5 or, instead, to show it going from no-bar-at-all (zero) to the new value of 5?

Right now, as you have already seen, animation takes place from zero to the new value, e.g. from no-bar-at-all to 10.
(negative case was not handled though, you are right that this is anyway a bug)

**Comment by ignacioch** [comment]
Hmm let me check again and update - will do in the next hour.

Sent from my phone, Sorry for typos.

On 31 Oct 2017, at 22:58, Panagiotis Spirou <notifications@github.com<mailto:notifications@github.com>> wrote:


So @ignacioch<https://github.com/ignacioch> for the cases you mentioned, bar should animate from current value to new value?
Or from zero to new value?
E.g. from 7 to animate down to 5 or, instead, to show it going from no-bar-at-all (zero) to the new value of 5?

Right now, as you have already seen, animation takes place from zero to the new value, e.g. from no-bar-at-all to 10.
(negative case was not handled though, you are right that this is anyway a bug)

**Comment by ignacioch** [comment]
OK, it should animate always from current value to new value.

**Comment by panagiotissp** [comment]
wait, so this applies to positive numbers to?

E.g. Team A has maximum score right now of 10.
Team B has 5 points (half the bar)
Team B scores 2 extra points now that it was their turn, so is goes to 7.
Should I animate from 5 to 7 or from 0 to 7?

If so, this changes the specs and the logic implemented right now on this

Otherwise, if case is:
- when score increases then animate from zero to new value (current implementation) 
- when score decreases then animate "from current to new value"
then we are on track and I need to implement 2nd case only

Waiting clarification

**Comment by ignacioch** [comment]
> Should I animate from 5 to 7 or from 0 to 7?

From 5 to 7 yes. Is it easy to do so? I can send you IOS logic if needed. If that's not easy or possible on Android I can communicate that to client.

**Comment by panagiotissp** [comment]
@ignacioch  Ok I will change the logic. (just for my clarification, were the specs always like that or did they change?)

But for the negative points thing, could you please send me a video on iOS of the following case:

Team A has 4 points, Team B has 2 points. 
It is time for Team A to play. They score -5 points. They click on 'next' and go to the Score page.
How the score page animation will be?

**Comment by panagiotissp** [comment]
(I'm creating a separate ticket to change logic of animation from current value to new value since I have fixed that)

**Comment by panagiotissp** [comment]
@ignacioch an extra ping here just to be sure you do not miss my question above

**Comment by ignacioch** [comment]
Ok will create the video as well but to answer  : 

> Team A has 4 points, Team B has 2 points.
It is time for Team A to play. They score -5 points. They click on 'next' and go to the Score page.
How the score page animation will be?

Team A new score is 0. So : 

team A : negative bar from 4 to 0.
team B : stays at 2 (which would be somewhere in the middle I assume, depending on your implementation ).

In my part, I am keeping the 3 scores you mentioned ( 0,2,4) to find out the max and then place the others on the screen accordingly.

Will create a video as well with exact the same numbers you said.
