### ISSUE TITLE
[Sudden death][Feedback round 1] UI

### ISSUE THREAD

**Issue by ignacioch** [labooltd/GameAndroid#57]
- [x] there should be no home button the first time the sudden death page loads.
- [x] Text is not visible. check : https://www.dropbox.com/s/6ipdn6stgj8ujf1/Photo%2029-10-2017%2C%2017%2004%2043.jpg?dl=0
- [x] There is some confusion on animation based on issue #33. Maybe I was not so clear and I confused you as well.

So, let me give you screenshots as well. Game goes into sudden death. You should see that : 
https://www.dropbox.com/s/8w1us9xe6u8tdqt/Photo%2030-10-2017%2C%2021%2030%2040.png?dl=0
All is correct so far, **there is no animation.**
After that point, we should see the normal score screen with animation.
https://www.dropbox.com/s/govbh9acvxx91qp/Photo%2030-10-2017%2C%2021%2031%2001.png?dl=0
I was confused with latest comment on #33, because you mentioned every time sudden death appears there is no animation - which is correct. 

Ennow oti sto ios einai separate screens, opote apo ekei kai meta, otan pathsw next vlepw to kanoniko score screen pou eixa kai sto kanoniko game ara, exoume animation kanonika. Is it clear? Do you want a video maybe?

**Comment by panagiotissp** [comment]
@ignacioch  for many different reasons I initially implemented and now still have 2 completely separate screens for 'score page' versions:
the "normal score page" and the "sudden death mode score page".

I believe that now I should leave that as it is and patch it with the animation that you mentioned above should still exist

**Comment by panagiotissp** [comment]
ok @ignacioch  for the 1st bullet: So what should happen when user clicks the hardware back button on this case?
