### ISSUE TITLE
[Sudden death][Feedback Round 1] UI II.

### ISSUE THREAD

**Issue by ignacioch** [labooltd/GameAndroid#58]
Next button on score pages when on sudden death is wrong ( it uses the same as sudden death but it should use the usual one)

==> https://www.dropbox.com/s/govbh9acvxx91qp/Photo%2030-10-2017%2C%2021%2031%2001.png?dl=0

**Comment by panagiotissp** [comment]
@ignacioch Do you mean to put the "next" button everywhere and only in the Sudden death with the popup to show the "play" button?

**Comment by ignacioch** [comment]
Yes - basically after you see the Sudden death for the first time ( this will be "play" ) everything else should be the same screen as score ( even if you have different files on Android ). So just like in score you see "Next" , we should see "Next" here as well [ except the first time the Sudden death appears as you said ]

**Comment by ignacioch** [comment]
Back to you - let me know for any questions.
