### ISSUE TITLE
[Winner][Feedback round 1] Wrong text.

### ISSUE THREAD

**Issue by ignacioch** [labooltd/GameAndroid#59]
Will send you the correct one.

**Comment by ignacioch** [comment]
Sorry the correct one is : 

- if jokers are OFF from settings  

 "Partagez" ;

- if jokers are ON : 

then use the test you use.

**Comment by panagiotissp** [comment]
@ignacioch  please review to be sure I understood correctly. What is done now:
- If jokers are off from secret settings, "partagez" is shown (and nothing is done after successful share)
- If jokers are on from secret settings AND jokers are still locked, then the text "Partagez votre score sur facebook pour déverouiller les jokers" is shown (and jokers are getting unlocked after successful share)
- If jokers are on from secret settings AND jokers have been unlocked, then "partagez" is shown (and nothing is done after successful share)
