### ISSUE TITLE
[Rules][Feedback Round 1] add text formatting.

### ISSUE THREAD

**Issue by ignacioch** [labooltd/GameAndroid#62]
Will send you details.

**Comment by ignacioch** [comment]
Forgot this one. By formatting I mean new lines.

"Objectif du jeu: Accumuler plus de points que l’équipe adverse (ou les équipes adverses) en répondant aux questions. \n\
Pour chaque question, 9 réponses sont proposées avec une valeur équivalente à leur difficultée (1,2 et 5 points). \
Attention, pour certaines questions, parmi les réponses proposées se trouvent des réponses-pièges qui retirent 5 points (les réponses pièges sont de fausses réponses). \n\
Comment jouer: \n\
-Se séparer en deux, trois ou quatre équipes composées d’un ou de plusieurs joueurs.\n\
-Choisir un nom (facultatif) et une couleur différente pour chacune des équipes. \n\
-Choisir le nombre de rounds (5,10,15 ou 20).\n\
Un round est terminé lorsque chaque équipe a répondu à une question.\n\
-Si vous le désirez vous pouvez sélectionner les catégories de questions que vous souhaitez utiliser au cours de la partie (minimum six).\n\
-Lire la question à l’équipe adverse\n\
-Sélectionner les réponses correctes citées par l’équipe adverse\n\
-Inverser les rôles et ainsi de suite\n\
Exemple:\n\
Prenons le cas d’une partie à deux équipes: A et B.\n\
Après avoir choisi les paramètres du jeu,\n\
un joueur de l’équipe B prend le portable en main et lit la question à l’équipe A; à compter du moment où il/elle appuie sur la touche  « Go » , l'équipe A dispose de 60 secondes afin de trouver le plus de réponses possibles.\n\
Lorsqu’ une réponse qui se trouve dans la liste est citée par l’équipe A, le joueur de l’équipe B doit  la sélectionner.\n\
Lorsque le temps est écoulé, le portable passe dans les mains d'un joueur de l’équipe A et le processus recommence dans l’autre sens.\n\
L’équipe gagnante est celle ayant accumulé le plus de points après la fin de la partie.\n\
En cas d’égalité du score, un round supplémentaire (mort subite) détermine le gagnant."

**Comment by panagiotissp** [comment]
@ignacioch  are you sure no \n is needed before "Attention"? (copying text below)

"Pour chaque question, 9 réponses sont proposées avec une valeur équivalente à leur difficultée (1,2 et 5 points). 
Attention,"

**Comment by panagiotissp** [comment]
@ignacioch I closed that, please check to be sure

**Comment by ignacioch** [comment]
Reopening - please text on top to be the French one [ Regles ]

**Comment by panagiotissp** [comment]
yeah I missed that, it is now fixed

**Comment by ignacioch** [comment]
Reopening - text is cut off.

the bold one is not visible 

"Objectif du jeu: Accumuler plus de points que l’équipe adverse (ou les équipes adverses) en répondant aux questions. \n
Pour chaque question, 9 réponses sont proposées avec une valeur équivalente à leur difficultée (1,2 et 5 points). 
Attention, pour certaines questions, parmi les réponses proposées se trouvent des réponses-pièges qui retirent 5 points (les réponses pièges sont de fausses réponses). \n
Comment jouer: \n
-Se séparer en deux, trois ou quatre équipes composées d’un ou de plusieurs joueurs.\n
-Choisir un nom (facultatif) et une couleur différente pour chacune des équipes. \n
-Choisir le nombre de rounds (5,10,15 ou 20).\n
Un round est terminé lorsque chaque équipe a répondu à une question.\n
-Si vous le désirez vous pouvez sélectionner les catégories de questions que vous souhaitez utiliser au cours de la partie (minimum six).\n
-Lire la question à l’équipe adverse\n
-Sélectionner les réponses correctes citées par l’équipe adverse\n
-Inverser les rôles et ainsi de suite\n
Exemple:\n
Prenons le cas d’une partie à deux équipes: A et B.\n
Après avoir choisi les paramètres du jeu,\n
un joueur de l’équipe B prend le portable en main et lit la question à l’équipe A; à compter du moment où il/elle appuie sur la touche « Go » , l**'équipe A dispose de 60 secondes afin de trouver le plus de réponses possibles.\n
Lorsqu’ une réponse qui se trouve dans la liste est citée par l’équipe A, le joueur de l’équipe B doit la sélectionner.\n
Lorsque le temps est écoulé, le portable passe dans les mains d'un joueur de l’équipe A et le processus recommence dans l’autre sens.\n
L’équipe gagnante est celle ayant accumulé le plus de points après la fin de la partie.\n
En cas d’égalité du score, un round supplémentaire (mort subite) détermine le gagnant."**

**Comment by ignacioch** [comment]
The quoted one is missing.
