### ISSUE TITLE
[Client feedback] Remove all English strings. Keep only default French strings

### ISSUE THREAD

**Issue by ignacioch** [labooltd/GameAndroid#63]
This came from clients : 

> 1) σε μια βερσιόν είναι το παιχνίδι γραμμένο στα αγγλικά (φώτο 11). Εμείς το θελουμε πάντα στα γαλλικά. Η βερσιόν του κινητού είναι 7.0 αν και σ αυτό το θέμα δεν νομίζω να έχει να κάνει με βερσιον. Τα γραφικά σ αυτό το κινητό έμοιαζαν με του δικού μου κινητού που είναι 4.4.4.

https://www.dropbox.com/s/b2tcnn7ni0vokvs/IMG-20171030-WA0011.jpg?dl=0

Why is that? Is it a setup issue/ android version/ phone or what?

**Comment by panagiotissp** [comment]
@ignacioch  Copying my answer from issue where you asked the same. 

"French is the default language, but if locality matches English version, then it is "smart" enough to use the localized strings, i.e. English in this case."

Do you think this might be the case for the customer's devices (one with English language in the system and the other in French)? You can test it yourself too just for double check before going back to customer.

I cannot imagine of sth else. Waiting for your reply/confirmation in order to close this issue.

**Comment by ignacioch** [comment]
That should be it yes - spoke with client. Can we make French the default language every time?? ( Except the places you had hardcoded the string in the app of course).

Is it possible / easy in Android?

Sent from my phone, Sorry for typos.

On 1 Nov 2017, at 12:35, Panagiotis Spirou <notifications@github.com<mailto:notifications@github.com>> wrote:


@ignacioch<https://github.com/ignacioch> Copying my answer from issue where you asked the same.

"French is the default language, but if locality matches English version, then it is "smart" enough to use the localized strings, i.e. English in this case."

Do you think this might be the case for the customer's devices (one with English language in the system and the other in French)? You can test it yourself too just for double check before going back to customer.

I cannot imagine of sth else. Waiting for your reply/confirmation in order to close this issue.

**Comment by panagiotissp** [comment]
@ignacioch I'm not 100% sure I understand correctly.

Does customer want to have **only** French strings in the app and no English at no case at all? (ok if I do not have a French version but only an English one, it will show that, but forget about this case)

If so, what's the point of the English strings provided in the xlsx file you have sent to me??

Anyway, it was a lot of work to put them. If we are 1000% sure that we want "no English version of app" at all, it is easy to remove it.

(To understand, imagine there are 2 files with strings, one in French the other on English. You select the 'default' one. And Android uses the 'default' - French - only except if device's language is the English one. In that case it will use English)

**Comment by ignacioch** [comment]
Yes last email said they want ONLY French. So in IOs I removed the file with the English translations. You can do the same on Android I assume.

> If so, what's the point of the English strings provided in the xlsx file you have sent to me??

I don't know - either initial plan was to have both or for us to understand what goes where.

**Comment by panagiotissp** [comment]
@ignacioch  I removed them, There should now be only French strings in all cases/devices. (if not, it means I have not been provided the French version)
