### ISSUE TITLE
[Score Page AND Sudden Death Page] Sound effect

### ISSUE THREAD

**Issue by panagiotissp** [labooltd/GameAndroid#64]
@ignacioch  sound effect on these pages should be before or after animation finishes?

**Comment by ignacioch** [comment]
Hmm good point - haven't heard about clients for that. Should we put it after?? What do you think is easier? Does animation have different sound?

I have an iOS bug on sounds which prevents me from testing it right now.

**Comment by panagiotissp** [comment]
@ignacioch  considering that the sound is like 1 second maximum, I believe playing it at the end of the animation, with the change of points, is the best. Implementation-wise, I'm not sure but probably it will not make big difference

Should I do it that way? 
(If yes, just keep in mind for the iOS app to be aligned finally)

**Comment by ignacioch** [comment]
OK let's do that, I will do the same in iOS.

Sent from my phone, Sorry for typos.

On 2 Nov 2017, at 20:09, Panagiotis Spirou <notifications@github.com<mailto:notifications@github.com>> wrote:


@ignacioch<https://github.com/ignacioch> considering that the sound is like 1 second maximum, I believe playing it at the end of the animation, with the change of points, is the best. Implementation-wise, I'm not sure but probably it will not make big difference

Should I do it that way?
(If yes, just keep in mind for the iOS app to be aligned finally)

**Comment by panagiotissp** [comment]
Closed by commit c646558f
