### ISSUE TITLE
[General] Double Check/Use new/List Missing All Images

### ISSUE THREAD

**Issue by panagiotissp** [labooltd/GameAndroid#67]
Relates to #30
Relates to #45 
Relates to #47

**Comment by panagiotissp** [comment]
- joker_give_question_img ( All 4 graphics )
Others provided in the new graphics. This is too small now compared to the new ones. It should be 300x300 too as the rest
![smaller-joker-img](https://user-images.githubusercontent.com/14311142/32459667-124c19ac-c339-11e7-9ea4-a159e719c6ba.PNG)


- clock image: Newly provided is 1000x1000 in xxxhdpi (whole screen width is 1280)
![probl-clock-image](https://user-images.githubusercontent.com/14311142/32460346-28cd32ae-c33b-11e7-8c15-7d95af897481.PNG)


- Round buttons selected and unselected inconsistent: 
I cannot anymore continue explaining this. I'm just attaching a screenshot showing the dimensions. I have removed all workaround in the code since these were also made inconsistent with the updated dimensions.
![probl-round-buttons](https://user-images.githubusercontent.com/14311142/32462487-309a8750-c342-11e7-8c2b-88ae8585b0fd.PNG)

**Comment by panagiotissp** [comment]
And in a nutshell:

- [ ] joker_give_question_img ( All 4 graphics )
- [ ] Question page clock image combined with the circular background header  
- [ ] Round buttons selected and unselected inconsistent
- [ ] 'triangle small arrow' image, cyan color 
- [ ] 'triangle small arrow' image, magenta color 
- [ ] Main menu popup both images

**Comment by ignacioch** [comment]
Ah just saw what you request - some of them already send in #30  ( copying link here as well to make it easier )

https://www.dropbox.com/sh/m53qzelqb8wyc3n/AABzqtzew2eILW3ZspdyvH0ga?dl=0

will check the rest as well.

**Comment by ignacioch** [comment]
Please tick/untick what works from you from the link above.

**Comment by panagiotissp** [comment]
@ignacioch  these are the needed/missing/problematic graphics I have found.
Issues #30 and #45 can be closed and let's handle the rest of missing graphics on the current issue to finish this story.

Hope you agree.
Please contact customers (again) asap.

**Comment by ignacioch** [comment]
Yes close the related ones and let's keep only this one - check the link on my comment, some of them are already provided. Will contact for the rest.

**Comment by panagiotissp** [comment]
@ignacioch  I updated the code with the new graphics in Main menu popup and with the Clock image.
The issue that I was referring to for the clock img-background top header is the distortion shown below in my screenshot (this is how it currently looks like):

![distortion](https://user-images.githubusercontent.com/14311142/32467030-cada19ac-c351-11e7-9211-f847d8a77cb0.PNG)

Should I wait for my suggested graphic or mark this thing as done too?

**Comment by panagiotissp** [comment]
Also about the round button thing @ignacioch 
what needs to be done seems pretty straightforward based on the screenshot I put:
- First of all, ALL buttons (5,10,15,20, selected and unselected versions) should have the same width. (width of unselected versions is 206 so I suppose all widths should be 206?!)

- Secondly, the huge empty space below the shadow in the unselected versions should be removed. Shadow should be the bottom of these graphics.

**Comment by panagiotissp** [comment]
@ignacioch I  am waiting for your answer on the above regarding the clock.
Also, I updated the comment(s) above with a 7th case of problematic graphic, the locked joker image.

**Comment by ignacioch** [comment]
Clock is the same as IOS - I will mark it as done.

**Comment by ignacioch** [comment]
Also marking joker_give_question_img ( All 4 graphics ) as done since joker is not used anymore.

**Comment by ignacioch** [comment]
Waiting on the rest graphics.

**Comment by ignacioch** [comment]
Locked joker image : https://www.dropbox.com/s/na0sr338sdgg7l9/LockedButton.png?dl=0
Triangle small magenta : https://www.dropbox.com/s/eay098kz11sxytw/triangle.png?dl=0
( if you need so ) Number 10 selected : https://www.dropbox.com/s/asazp76ym449hwh/selected10_v2.png?dl=0

**Comment by ignacioch** [comment]
cyan colour provided as well - closing the issue - if something is not working reopen.

**Comment by panagiotissp** [comment]
I'm reopening current issue (and close all other relevant ones) since we have  again  issues with the updated graphics.

**Comment by ignacioch** [comment]
try this - https://www.dropbox.com/s/p6v8guwdbrzmhka/android.7z?dl=0

**Comment by ignacioch** [comment]
triangle cyan --> https://www.dropbox.com/s/9xakf0ns8qte4o9/triangle_cyan.png?dl=0
triangle magenta -->  https://www.dropbox.com/s/vb4qkklfp1oylox/triangle.png?dl=0

**Comment by ignacioch** [comment]
selected buttons new version --> https://www.dropbox.com/sh/jv90a79sgbk19ko/AAClaZf1Hw6m9D6Cn5OX_DAQa?dl=0
