### ISSUE TITLE
[Mail Page] Functionality to unlock jokers when user inserts email

### ISSUE THREAD

**Issue by panagiotissp** [labooltd/GameAndroid#68]
@ignacioch
Is this still a thing? (I have asked for this in the past but I got no answer)

If yes, it needs implementation.
Should I set as logic to unlock jokers with whatever email a user inserts?
This does not make a lot of sense. Users may put invalid emails that way.
And if we insert a verification process, then the flow where the app sends a verification email and the user opens it and they are redirected successfully to the app with the jokers unlocked needs a lot of implementation and is not simple at all:
Sending verification email means that there should be the corresp db table that stores the "registered users". Because otherwise the inf might be lost (e.g. if user uninstalls and installs the app again),
temporary tokens probably need to be generated, extra security things should be taken into account, logic of where to redirect the user when they click the email should be applied etc etc. 

Please advise asap on this one.

**Comment by ignacioch** [comment]
I was thinking about that the other day - we need to implement it but without any check ( only that it's an email address / valid or not we don't care).

Before you implement let me confirm with the clients - ideally I would like it removed completely. So far it's what you said - user puts whatever email --> jokers are unlocked.

Sent from my phone, Sorry for typos.

On 5 Nov 2017, at 18:22, Panagiotis Spirou <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #68<https://github.com/labooltd/GameAndroid/issues/68> to @ignacioch<https://github.com/ignacioch>.

**Comment by ignacioch** [comment]
So we have news from client.

They want this : 

Open the page as we do right now. Right now they dont want data to be saved anywhere, they might add it themselves or hire someone else to do it in the future. So they want that : 

1) When the user inserts an email, this handler or whatever should call a function 

```
saveToFirebase( string email ){

}
```

which should now be empty and returns true all the time. 

2) on return since it's always true we continue like save was successful.

is it clear?

**Comment by panagiotissp** [comment]
@ignacioch so in order to be 100% aligned, currently on the Mail Page, when user inserts an email (there is a basic email validation check too - to be in the form of _X@Y.Z_ I think ) then this is what is shown:
![screenshot_20171119-003424](https://user-images.githubusercontent.com/14311142/32985359-d5306176-ccc1-11e7-927a-08953bcec7d0.png)

And when they click the 'tick' button this is what is shown:
![screenshot_20171119-003442](https://user-images.githubusercontent.com/14311142/32985361-d9d34d42-ccc1-11e7-93cb-daca42bc8c01.png)


1) We want when the tick button is clicked, this empty method that you provided to be called (without doing anything obviosuly), right?
2) What should be done with jokers anyway? Should jokers be unlocked in current implementation or I should not do anything (and it will be handled in the future implementation of that empty method) ?

Waiting for your final reply on this one before I handle it


so ok yes, yes when inserts email and hits "Enter" (or whatever button we have in the UI - not sure right now), this method should be called, and the implementation of it will just be empty as you provided it. Did I understand correctly?
If yes, then what is not clear is if the jokers should be unlo

**Comment by ignacioch** [comment]
1. yes
2. no this empty function will return true - like it validated the email and saved it and therefore you proceed with unlocking the jokers.
3. i think on return, this page closes and we get back with the jokers now being unlocked.

**Comment by ignacioch** [comment]
is that clear?

so basically, add the email, click yes, and return with the jokers unlocked.
But in the code, this should be something like : 

checkClicked -> addToFirebase -> return True -> callback is called -> if True unlock jokers and return.

**Comment by panagiotissp** [comment]
@ignacioch this should be implemented on commit d21b337
Some bullets on the implementation in order to be sure we are aligned:
* Method requested is called when a valid email has been inserted and Tick button is clicked
* Jokers are unlocked in that case
* On hitting back button, we return to the previous screen, I.e. the **NoFB Page and not the Game Settings P2**
* I removed the text from being shown when user enters valid email and clicks Tick button. The text says that "you will receive a confirmation email" etc, which currently is not the case so I suppose it should be implemented inside the method saveToFirebase.

@ignacioch  I'm closing this, but I wait for your comment below anyway when you see this, that we are aligned...
