### ISSUE TITLE
[Options] resturer achats

### ISSUE THREAD

**Issue by ignacioch** [labooltd/GameAndroid#7]
In IOS, there is a functionality restore options. This is when you buy something and you click restore, you can undo all purchases - this is being handled by Apple ( there are some terms and conditions ). If google has the same, then do so. To give you a workflow.

1. i have bought the no ads
2. i click restore
3. (internal google stuff) success
4. app gets the response, it makes it behave as having ads again.

**Comment by panagiotissp** [comment]
Based on that: https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/StoreKitGuide/Chapters/Restoring.html

From that I understand that "restore purchases" on IOS will not 'undo all purchases'. Instead it will make a call to the store and retrieve the purchases that the user has already made.

If so, then in android this can automatically be done on each start of the app. So, I may not need that button. 
1) Am I correct that this is 'restore purchases' purpose and not what you described?
2) In IOS, if user has already purchased sth but right now mobile is offline (no internet), how do you handle this case?

**Comment by ignacioch** [comment]
Εχεις δικιο, οπως τα λες ειναι,

1. If you can do it on app init then do it. On IOS it is a UX rule that you should have it as explicit button.
2. On current design, if there is no internet we don't connect to the servers, we just give a popup saying 'No Internet'. I would avoid complex logic, like buffering the purchase and do it later once we have internet etc.

**Comment by panagiotissp** [comment]
It seems to be possible to be implemented on app init. So, when user opens the app there would be 2 options on handling already purshaced items:
- I try everytime on init to get any purchased items. If I get a 'no internet' error then show a 'no internet' message and for any games played until user opens the internet connection it will be assumed that no purchases are made. This is the way the ios handles it?
- I store locally on customers' smartphone the purchased items. This would have a better UX probably, but in general is not a good approach at all from what I know.

So, what is the suggested approach?

**Comment by ignacioch** [comment]
Well, based on that :

http://stackoverflow.com/questions/35271870/how-can-i-implement-restore-purchase-in-android

"If you are implemented the InApp Purchase using v3 you need not worry about the restore Purchase implementation. You can query the inventory and catch the existing Purchase information."

Γενικα δες αν ειναι απαραιτητο, στην αππλε δεν μπορεις να κανεις submit to app without restore. if we can, then let's skip it for now.

**Comment by panagiotissp** [comment]
Yes, this is what I mean, I can try to query the inventory and get the purchase info, but what if I try to query on app init and internet is off on the mobile? Is there any specific workflow? Or I just ignore this case?

**Comment by ignacioch** [comment]
If internet is off - show default android error alert that says : Internet is required.Try again.

Otherwise proceed with what you said.

**Comment by panagiotissp** [comment]
Check if internet is on.
- If yes, it is supposed to fetch any purchased items from the store, as normal (it is part of issue #32 )
- If no, then the following popup is shown:
"Internet is required for any purchased items to be loaded. Try again.
(gameplay will continue with no purchased item)"

No other handling is needed for 'restoring purchases'.
(Corresp button will not be included in the UI of Options page since it is not mandatory)
