### ISSUE TITLE
[Jokers] General logic of what is enabled or not.

### ISSUE THREAD

**Issue by ignacioch** [labooltd/GameAndroid#70]
This applies only when jokers are ON in secret settings.

In general jokers are locked and can be unlocked via 1. Facebook share 2. Giving email (we have extra pages for this) 3. Buying a joker pack 
When unlocked via options 1 & 2 (facebook or e-mail) then only 1 joker is available ( the first one ) for "attacking jokers" (and 1 "defensive jokers" is available )
The other 2 should be locked and can only be unlocked if bought together as a pack. 

If the jokers are unlocked with option 3 ( buying a pack ) then all jokers are available nothing is locked.

**Comment by panagiotissp** [comment]
@ignacioch  please be more specific, i.e. instead of 'good joker 1', '+ 2 points joker', instead of 'evil joker 1' to be 'divide by 2 joker' etc.

Also an extra note that there are 4 good jokers (I think), the 2 of them being interchangeable depending if the teams playing are 2 or more (then we show the corresp joker).
But the clarification I asked will handle this case too (this sis just fyi, in order not to forget to clarify this extra joker)

**Comment by ignacioch** [comment]
Ok so we have the following jokers : 

Attacking -

A1 : x2 ( multiplies everything x2 )
A2 : +2 ( gives every question 2 points extra )
A3 : change question

Defensive : 

D1 : /2
D2 : -1
D3 : time to 15 secs.

Based on what the client wants, **on a game with secret settings ON for jokers** : 

- [ ] we start with all the jokers locked ( meaning you cannot toggle the switch )
- [ ]  can be unlocked via 1. Facebook share 2. Giving email (we have extra pages for this) 3. Buying a joker pack
- [ ] on option 1/2 you can play using jokers ( you can toggle the switch ) but only jokers A1/D1 are available.
- [ ] jokers A2/A3 are available if you buy either the attacking joker from the store, or the packet for both jokers
- [ ] - [ ] jokers D2/D3 are available if you buy either the defensive joker from the store, or the packet for both jokers

Probably you are missing graphic for A2 - this one replaced the question of interchangeable turns. This is removed because it brings more issues ( the new A2 is much simpler )

**Comment by panagiotissp** [comment]
No I have that graphic too.
The "interchangeable turns" joker was an extra one. I knew about 4 good jokers in total, this is what I have implemented based on the initial pdf file I had been provided.

So, I will remove this extra joker functionality and use just the jokers you mentioned.

**Comment by panagiotissp** [comment]
@ignacioch  this is done.
Only missing related to unlock of jokers is to emulate process when purchasing successfully the Premium package.

This should be handled on the issue #32 as part of implementing the full Store functionality (since also this purchase will anyway be done in Store page).
