### ISSUE TITLE
[Question] package naming?

### ISSUE THREAD

**Issue by ignacioch** [labooltd/GameAndroid#71]
I see lots of packages named like these : 

`package com.spiroupanagiotis.gameod.Billing;`

My question is how that relates ( and if at all ) to the developer account? Eg they might use a diffferent package name ?

is it easy to change ( rename ) and not break stuff? Eg :` com.devineuf.android.devine` ideally should replace the `com.spiroupanagiotis.gameod` 

But I would leave that to the very end.

**Comment by panagiotissp** [comment]
@ignacioch 
First of all, yes package can be renamed.

There are conventions for the package naming. 
Here they are described well: https://stackoverflow.com/questions/8075162/what-should-be-the-package-name-of-android-app

And here a good example for adobe, is included: https://stackoverflow.com/questions/6273892/android-package-name-convention

The simple rule that applies to our case I think is that there is a domain owned, so the package should be on this format of:

`fr.devineuf`

Is that right?

PS1: Does Current issue includes 1st bullet of issue #72 for changing name from 'GameOd' to 'DevineUf' ?

PS2: For my reference and yours if you want more info: https://developer.android.com/studio/build/application-id.html

**Comment by ignacioch** [comment]
yes use the convention above. Also, yes, let's change the name - you can link those issues or close them together once you fix it. Official app name is DevineUf
