### ISSUE TITLE
Dimensions for logo / name change

### ISSUE THREAD

**Issue by ignacioch** [labooltd/GameAndroid#72]
- [x] Name should be changed from GameOd to DevineUf
- [x] How many images and what dimensions do we need for the logo that appears on the background of the phone or any related image ( launcher icon etc)?

Found that but how up to date is : 
https://stackoverflow.com/questions/12768128/android-launcher-icon-size

https://developer.android.com/guide/practices/ui_guidelines/icon_design.html

**Comment by panagiotissp** [comment]
So @ignacioch  
from what I understand the 1st bullet is part of issue #71 so when that will be closed I will confirm and mark this one as done too.

So let's focus on the icons.

Yes the links you posted are correct.
* First of all I do not see any other requirement than the launcher icons. We do not need notification icons, action bar icons etc.
* I do not understand 100% if the 'adaptive' icons are necessary. I think not https://stackoverflow.com/questions/45620765/icons-in-android-o
It seems that the current icon will be included in a round layout, based on what this stackoverflow says.
So, based on that, it is not necessary, ok it would be probably good to have one, but it introduces *a lot of* new guidelines to create those, it is a separate section in the link you posted, and it only works for sdk 26+ which based on the current dashboard here https://developer.android.com/about/dashboards/index.html
it is like 0.3% globally. So, for me, no, it is not necessary, but what's your opinion?
* For the launcher icons, there are some design guidelines here: https://material.io/guidelines/style/icons.html# which are simple enough _("Android expects product icons to be provided at 48dp, with edges at 1dp")_.

So, we want 5 different launcher icons(mdpi, hdpi, xhdpi, xxhdpi, xxxhdpi), and for dimensions, android expects 48dp, which translates in pixels to the numbers of answer 3 on stackoverflow link you originally posted:
48 × 48 (mdpi)
72 × 72 (hdpi)
96 × 96 (xhdpi)
144 × 144 (xxhdpi)
192 × 192 (xxxhdpi)

* I did not know the needed 512 × 512 for Google Play store but it is true. 
I think the guide here will help a lot to see if anything more is required, just to be sure: https://support.google.com/googleplay/android-developer/answer/1078870


I don't think there is something more for me to do on this issue now.
I will put it to you to to handle the needed graphics part and/or pass the link to the customer (or check it yourself, not sure) regarding the upload of the app process to Google play in order not to meet something unexpected finally

**Comment by panagiotissp** [comment]
@ignacioch  If you think it would be better to close current issue when you confirm we have a clear answer to what is needed as graphics (hopefully these 6 I mentioned above) and create a separate ticket that waits for these graphics, then feel free to do it

**Comment by ignacioch** [comment]
closing - i will put new graphics ( those included ) under the general
