### ISSUE TITLE
Stats popup.

### ISSUE THREAD

**Issue by ignacioch** [labooltd/GameAndroid#73]
The one you requested the cyan triangle. I have the triangle to send to you but clients also said :
- would it be easier to use the dialog box there as well? No toast , a dialog box like the one that appears when you click to buy for example, with an OK button at the bottom.

**Comment by panagiotissp** [comment]
@ignacioch  no it is not easier at all. Right now the only thing I have to do is to change an image with the new one provided and that's it, so let's stick to the original specs

(you may close current issue if that is enough)

**Comment by ignacioch** [comment]
ok then use this : https://www.dropbox.com/s/7lgdft6azxj7eat/triangle_cyan.png?dl=0

**Comment by panagiotissp** [comment]
Closing this. All remaining graphics problems *should* be handled under issue #67
