### ISSUE TITLE
[Client Feedback] 10 rounds.

### ISSUE THREAD

**Issue by ignacioch** [labooltd/GameAndroid#74]
When you click 10 rounds, you still play 5. I think also the 5 does not work as expected( probably for debug reasons )

**Comment by panagiotissp** [comment]
This should have already been fixed @ignacioch .

We should somehow keep a note/put a label of what remains to be confirmed maybe (if this already done maybe by the customer, to have in mind what to review to be sure that it was fixed, then I can just close issues as usual)

**Comment by panagiotissp** [comment]
Ok this is done already in the near past (maybe 1-2 apks difference with what customer reviewed).
Closing this
