### ISSUE TITLE
[Client feedback] Gap on questions

### ISSUE THREAD

**Issue by ignacioch** [labooltd/GameAndroid#76]
I am not sure what to respond to that - need your opinion.

Copying from clients : 

> 6) Android: Σε καποιες κινητα εχει μεγαλο κενο αναμεσα στις 9 απαντησεις και το κατω της σελιδας

which is true. is that by design? if you give me a reason why, I can comment back that this is to "work with different screens" for example.

I assume what they want is to take the whole screen always and re-adjust the size based on the screen sizes.

I dont know if that's feasible on Android - so please tell me what to respond? is that a limitation on Android? or can we work on that?

**Comment by panagiotissp** [comment]
Also there is the following feedback fomr customer which is more generic and includes the opposite issue too:

> Too much space under the final answer, especially on bigger screens.
> 
> For version 4.2.2 (Samsung galaxy 3 mini) we have the following  issue: Sometimes, we have to scroll down to see all answers, This happens ONLY when some answers take more than one line and there is a kotsana, so it is not very common. Ideally we would not have to scroll, but if there is no other way on small screens, then only the answers should scroll up and down, and not the question and clock.

**Comment by panagiotissp** [comment]
@ignacioch  SO I implemented what they said:
* Answers are evenly distrubuted in UI.
* If scrolling applies, since this might be the case for some Android device and is completely natural, top header will remain fixed to the top

Screenshots of before and after in my devide evenly distributing answers. Please confirm:


Before:
![q-before](https://user-images.githubusercontent.com/14311142/33031634-89f293ca-ce27-11e7-8c4f-8b39b77cf6d5.PNG)


After:
![q-after](https://user-images.githubusercontent.com/14311142/33031645-93867eb0-ce27-11e7-95b8-e5e9bd753862.PNG)

**Comment by ignacioch** [comment]
Seems ok from the screenshots.

Sent from my phone, Sorry for typos.

On 20 Nov 2017, at 17:19, Panagiotis Spirou <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #76<https://github.com/labooltd/GameAndroid/issues/76> via 1d1650d<https://github.com/labooltd/GameAndroid/commit/1d1650d94392b218f8aa7f139e918aef2b502b34>.

**Comment by ignacioch** [comment]
Can you confirm if that's closed - it seemed ok but on the latest apk i can see some gap ( like the 1st screenshot you send me ) - I can send you screenshot if needed.

**Comment by ignacioch** [comment]
also, on the same, if you look on the screenshots above + phone, the clock is not centered properly. Do we need different graphics ? or sth we can fixed ( to roloi dn einai sthn mesh tou hmikyklioy - an mporei na erthei 2-3 pts left )

**Comment by panagiotissp** [comment]
@ignacioch this is supposed to have been already discussed, issue #67, my first comment, bullet 2

**Comment by panagiotissp** [comment]
and also a comment of me rementioning the issue again a little below, 20 days ago...

**Comment by ignacioch** [comment]
True, checking what I have. How about the gap? I can still see it

[image1.JPG]

Sent from my phone, Sorry for typos.

On 26 Nov 2017, at 12:36, Panagiotis Spirou <notifications@github.com<mailto:notifications@github.com>> wrote:


and also a comment of me rementioning the issue again a little below, 20 days ago...

**Comment by panagiotissp** [comment]
@ignacioch for the evenly distributed answers layout, you are right.
I overwrote a file by mistake (2 lines of code were reverted).
I fixed that in the commit referenced above and I'm uploading now 2 new release apks for you to have a quick look in order to confirm.

**Comment by ignacioch** [comment]
https://www.dropbox.com/s/p0yfgi2onsgu4el/Clock_V2-xxxhdpi.psd?dl=0

for the new psd for clock. if you cant open it let me know and I will do it for you.

**Comment by panagiotissp** [comment]
@ignacioch as we discussed, please provide not a psd but an image since I cannot open it.
And also we need 4 images (for the different colors) and not only one.
So I'm putting this task on you

**Comment by ignacioch** [comment]
nomizw dn mou esteilan to swsto - gt dn mou esteilan olo to background : to exw se ola ta colours alla des an sou kanw afto arxika

![clockcopyimage](https://user-images.githubusercontent.com/1605985/33245449-dfb3476e-d2ff-11e7-899d-9c6e93286968.png)
![layer3image4](https://user-images.githubusercontent.com/1605985/33245450-dfc76bc2-d2ff-11e7-8ed2-2571d2545146.png)

**Comment by ignacioch** [comment]
plus mou fainetai terastia h eikona :/

**Comment by ignacioch** [comment]
to clock einai 326 x 370 - toso to perimenes peripou?

**Comment by panagiotissp** [comment]
@ignacioch 

current one is 306x347 ... so the above is bigger indeed...
Should I try to use that or not?
It will not anyway be simple since I should do "little hacks" to make the 2 layouts you provided above for the one to be above the other etc, instead of having just one image to be shown...

I think it will be best to just request that again. One last time, and if it is provided wrong, ok.... we will not do this forever

What do you think?

**Comment by ignacioch** [comment]
requested as we discussed on messenger.

**Comment by ignacioch** [comment]
![magenta](https://user-images.githubusercontent.com/1605985/33326116-e6250c16-d44b-11e7-9f6d-b549ea83258d.png)

if that's ok i will send the other colours.

**Comment by ignacioch** [comment]
![blue](https://user-images.githubusercontent.com/1605985/33349062-85b3f05a-d490-11e7-9c76-75dd265f3e1d.png)
![cyan](https://user-images.githubusercontent.com/1605985/33349063-85c67bda-d490-11e7-9ba8-5ad630223356.png)
![orange](https://user-images.githubusercontent.com/1605985/33349064-85d8efd6-d490-11e7-8823-2932e31a18a7.png)

**Comment by panagiotissp** [comment]
@ignacioch as we said these images are not the same colors as the ones initially provided. (magenta has the least difference by far, that's why I could not tell initially when I tested it. Blue was the one that made me see the difference actually in the quick testing)

Waiting for your feedback based on what we said that you will request the ad-hoc colors only for this case.....

**Comment by panagiotissp** [comment]
@ignacioch please reopen if we get colors codes in the next 2-3 hours.
Otherwise, I will not make again a change after today for this ticket.
Customer will handle it on their side

**Comment by ignacioch** [comment]
pou evales ta global variables me ta codes? can you point out? 
alsom well technically tomorrow as well can work but let's see what we get.

**Comment by panagiotissp** [comment]
app\src\main\res\values\colors.xml

**Comment by ignacioch** [comment]
cyan : 00A79D
orange : FBA3AF
cyan : 2A388F
magenta : D91B5B

**Comment by ignacioch** [comment]
copying images + the colours again in case i did a paste error.

**Comment by ignacioch** [comment]
![blue](https://user-images.githubusercontent.com/1605985/33402141-893e5148-d553-11e7-946e-8b3a734b2fda.png)
![colors](https://user-images.githubusercontent.com/1605985/33402142-895b6da0-d553-11e7-9f20-495c0ec61fb3.png)
![cyan](https://user-images.githubusercontent.com/1605985/33402144-89789a7e-d553-11e7-820f-999aeedd9d6c.png)
![magenta](https://user-images.githubusercontent.com/1605985/33402145-89958f80-d553-11e7-93be-a68ded25cbff.png)
![orange](https://user-images.githubusercontent.com/1605985/33402146-89b02002-d553-11e7-8ee5-29feedbdccdd.png)

**Comment by ignacioch** [comment]
new colours are provided ( i think images are not needed - you already had them )

**Comment by panagiotissp** [comment]
Closed by commit f7f01dbab
