### ISSUE TITLE
[Store] 

### ISSUE THREAD

**Issue by ignacioch** [labooltd/GameAndroid#79]
Just not to forget this item.

There is also the item to purchase in Options > Pas de Pub ( which will hide the ads if bought ).

**Comment by panagiotissp** [comment]
@ignacioch  this should have already been handled in commit 10bc0f11 
Closing this task (I had forgotten 3 days ago)

**Comment by ignacioch** [comment]
Works - please add the following : 

when bought, default is off ( we had done so I think in a previous issue ) but switch is not togglable - you can't put it to ON. it always stays to off.

**Comment by ignacioch** [comment]
reopening.
