### ISSUE TITLE
Random crashes.

### ISSUE THREAD

**Issue by ignacioch** [labooltd/GameAndroid#85]
- Kollaei stin selida me tis palioteres partides se kapoia kinita (version 4.4.2) kai se alla den svinontai oi partides (4.4.4)

Not sure ti mporoume na kanoume edw - an mporeis na to trekseis emulator na deis. dn mporw na katalavw ao to feedback ti shmainei afto kai giati, isws des kana warning.

**Comment by panagiotissp** [comment]
This is a bug.
It is a specific case and if we reach there, app crashes ( from a quick look, do not remove correctly 1 value from shared prefs, but of course needs more investigation).
It is actually a subset and relates with issue #82

**Comment by panagiotissp** [comment]
Closed by commit 14f7c6c
