### ISSUE TITLE
[ Previous Game ] workflow

### ISSUE THREAD

**Issue by ignacioch** [labooltd/GameAndroid#92]
Clicking on a previous game, opens the game directly, it should not. In iOS you select the previous game, then the play arrow appears on the down bar and to play you need to press the arrow.

**Comment by ignacioch** [comment]
You should the graphics as well , it's the play triangle ( not the arrow )

**Comment by ignacioch** [comment]
ok since you asked me yesterday - i dont have graphics here for the row being highlighted when selected - on ios i do : 

 cell.backgroundColor = [UIColor clearColor];

so can you sth on Android to look like iOS ? or to make clear row is selected? chagen opacity/alpha sth similar?

**Comment by panagiotissp** [comment]
Closed by commit 3329ad69
