### ISSUE TITLE
[ Game Settings ] Spacing 

### ISSUE THREAD

**Issue by ignacioch** [labooltd/GameAndroid#98]
Still this looks unclear to me but : 

> All the "joker button section" and the "foot mode section" should be a bit lower, not to be so close to the "rounds buttons", or so far from the "question category button".

**Comment by panagiotissp** [comment]
This is not simple at all since in Android dimensions and spaces are generally dynamic.
It is always a best effort work.
@ignacioch  please provide a screenshot and I will try to match. This is to subjective for me to know what is considered "a bit lower" and what is "a bit higher"

**Comment by panagiotissp** [comment]
@ignacioch please provide screenshots of Game Settings Page 2 for the 3 cases:
* NoJokersVersion (disabled from secret settings)
*Jokers On but still locked
* Jokers On and unlocked

**Comment by ignacioch** [comment]
this should ok - https://www.dropbox.com/s/tym39mg704kx85k/Photo%2019-11-2017%2C%2017%2015%2051.png?dl=0

Basically only thing is to put an extra gap of a couple of px( or pts ) under the buttons. Can't give you exact number so lets try it - if we cant do anything better I will say this is due to Android restrictions.

**Comment by panagiotissp** [comment]
The UI is now in the following way (putting screenshots of all 3 cases):

![jokersonlocked](https://user-images.githubusercontent.com/14311142/32995374-f74549e2-cd7b-11e7-99a7-22d4a119e5ae.PNG)

![jokersonunlocked](https://user-images.githubusercontent.com/14311142/32995375-f7698d5c-cd7b-11e7-98c9-e82d12d8a943.PNG)

![jokersoff](https://user-images.githubusercontent.com/14311142/32995376-f78889f0-cd7b-11e7-950b-5d344ec18d28.PNG)

**Comment by panagiotissp** [comment]
@ignacioch please confirm the above screenshots as a quick look
